//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ErrorCode.proto
namespace fogs.proto.msg
{
    [global::ProtoBuf.ProtoContract(Name=@"ErrorID")]
    public enum ErrorID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=1)]
      FAILED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_UNCONNECTION", Value=49)]
      DB_UNCONNECTION = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_QUERY_FAILED", Value=50)]
      DB_QUERY_FAILED = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_QUERY_EMPTY", Value=51)]
      DB_QUERY_EMPTY = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_UNKONOW_OPERATION_TYPE", Value=52)]
      DB_UNKONOW_OPERATION_TYPE = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_GAME_VERSION_ERROR", Value=100)]
      LOGIN_GAME_VERSION_ERROR = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RESOURCE_VERSION_ERROR", Value=101)]
      LOGIN_RESOURCE_VERSION_ERROR = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_VERIFY_FAILED", Value=102)]
      LOGIN_VERIFY_FAILED = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SERVER_CLOSED", Value=103)]
      LOGIN_SERVER_CLOSED = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SERVER_BUSY", Value=104)]
      LOGIN_SERVER_BUSY = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SERVER_ERROR", Value=105)]
      LOGIN_SERVER_ERROR = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_SESSION", Value=106)]
      INVALID_SESSION = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_ACCOUNT_FAILED", Value=107)]
      LOGIN_ACCOUNT_FAILED = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SERVER_REPEAT", Value=108)]
      LOGIN_SERVER_REPEAT = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_EMPTY_CDKEY", Value=109)]
      LOGIN_EMPTY_CDKEY = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_WRONG_PASSWORD", Value=110)]
      LOGIN_WRONG_PASSWORD = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_ALREADY_ACCOUNT", Value=111)]
      LOGIN_ALREADY_ACCOUNT = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_ANOTHER_PLAYER", Value=112)]
      LOGIN_ANOTHER_PLAYER = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOADING", Value=113)]
      LOGIN_LOADING = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SDK_VERIFY_FAILED", Value=114)]
      SDK_VERIFY_FAILED = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVAILD_CDKEY", Value=115)]
      INVAILD_CDKEY = 115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCOUNT_ALREADY_LOGIN", Value=116)]
      ACCOUNT_ALREADY_LOGIN = 116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCOUNT_FROZEN", Value=117)]
      ACCOUNT_FROZEN = 117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCOUNT_MANAGED", Value=118)]
      ACCOUNT_MANAGED = 118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCOUNT_SILENT", Value=119)]
      ACCOUNT_SILENT = 119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRESHMAN", Value=120)]
      FRESHMAN = 120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KICK_OFFLINE", Value=121)]
      KICK_OFFLINE = 121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_OWNED_CAPTAIN", Value=130)]
      NOT_OWNED_CAPTAIN = 130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_OWNED_CAPTAIN", Value=131)]
      ALREADY_OWNED_CAPTAIN = 131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_IN_PLAY", Value=132)]
      ALREADY_IN_PLAY = 132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_SESSION_FAILED", Value=150)]
      CREATE_SESSION_FAILED = 150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_FIND_PLAYER", Value=200)]
      NOT_FIND_PLAYER = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_NAME", Value=201)]
      INVALID_NAME = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPEATED_NAME", Value=202)]
      REPEATED_NAME = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_NUM", Value=210)]
      INVALID_NUM = 210,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REACH_MAX", Value=300)]
      REACH_MAX = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_MONEY", Value=301)]
      NOT_ENOUGH_MONEY = 301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_DIAMOND", Value=302)]
      NOT_ENOUGH_DIAMOND = 302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_STUFF", Value=303)]
      NOT_ENOUGH_STUFF = 303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_LEVEL", Value=304)]
      NOT_ENOUGH_LEVEL = 304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_HP", Value=305)]
      NOT_ENOUGH_HP = 305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_CHALLENGE_TIMES", Value=306)]
      NOT_ENOUGH_CHALLENGE_TIMES = 306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCH_LOSE", Value=307)]
      MATCH_LOSE = 307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_HONOR", Value=308)]
      NOT_ENOUGH_HONOR = 308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_SWEEP_CARD", Value=309)]
      NOT_ENOUGH_SWEEP_CARD = 309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_PRESTIGE", Value=310)]
      NOT_ENOUGH_PRESTIGE = 310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_PRESTIGE2", Value=311)]
      NOT_ENOUGH_PRESTIGE2 = 311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_HONOR2", Value=312)]
      NOT_ENOUGH_HONOR2 = 312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_REPUTATION", Value=313)]
      NOT_ENOUGH_REPUTATION = 313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_HP2", Value=314)]
      NOT_ENOUGH_HP2 = 314,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_CHALLENGE_TIMES2", Value=315)]
      NOT_ENOUGH_CHALLENGE_TIMES2 = 315,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_VIP_LEVEL", Value=320)]
      NOT_ENOUGH_VIP_LEVEL = 320,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPEAT_GET_AWARD", Value=321)]
      REPEAT_GET_AWARD = 321,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VIP_AWARD_ALREADY_GET", Value=322)]
      VIP_AWARD_ALREADY_GET = 322,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_SIGN", Value=323)]
      NOT_ENOUGH_SIGN = 323,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPEATED_SIGN", Value=324)]
      REPEATED_SIGN = 324,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_MISS_SIGN", Value=325)]
      NOT_MISS_SIGN = 325,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SIGN_BEFORE_APPEND_SIGN", Value=326)]
      SIGN_BEFORE_APPEND_SIGN = 326,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAREER_SECTION_LOCK", Value=350)]
      CAREER_SECTION_LOCK = 350,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAREER_CHAPTER_LOCK", Value=351)]
      CAREER_CHAPTER_LOCK = 351,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAREER_SECTION_FINISHED", Value=352)]
      CAREER_SECTION_FINISHED = 352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAREER_CHAPTER_FINISHED", Value=353)]
      CAREER_CHAPTER_FINISHED = 353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAREER_NOT_ALL_SECTION_FINISHED", Value=354)]
      CAREER_NOT_ALL_SECTION_FINISHED = 354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD_SECTION_AWARD_FAILED", Value=355)]
      ADD_SECTION_AWARD_FAILED = 355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD_CHAPTER_AWARD_FAILED", Value=356)]
      ADD_CHAPTER_AWARD_FAILED = 356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAREER_SECTION_NOT_COMPLETE", Value=357)]
      CAREER_SECTION_NOT_COMPLETE = 357,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAREER_STAR_NUM_LACK", Value=358)]
      CAREER_STAR_NUM_LACK = 358,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAREER_STAR_AWARD_ALREADY_GET", Value=359)]
      CAREER_STAR_AWARD_ALREADY_GET = 359,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_ALREADY_GET", Value=360)]
      ROLE_ALREADY_GET = 360,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SWEEP_NEED_FULL_STAR", Value=361)]
      SWEEP_NEED_FULL_STAR = 361,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_OWNED_ROLE", Value=400)]
      NOT_OWNED_ROLE = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_OWNED_ROLE", Value=401)]
      ALREADY_OWNED_ROLE = 401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_PIECES", Value=402)]
      NOT_ENOUGH_PIECES = 402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL_LIMIT_QUALITY", Value=403)]
      LEVEL_LIMIT_QUALITY = 403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_OWNED_EXERCISE", Value=404)]
      NOT_OWNED_EXERCISE = 404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXERCISE_REACH_MAX", Value=405)]
      EXERCISE_REACH_MAX = 405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXERCISE_QUALITY_BIG_THAN_ROLE_QUALITY", Value=406)]
      EXERCISE_QUALITY_BIG_THAN_ROLE_QUALITY = 406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TALENT_LIMIT_STAR", Value=407)]
      TALENT_LIMIT_STAR = 407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_EXERCISE_QUALITY", Value=408)]
      NOT_ENOUGH_EXERCISE_QUALITY = 408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL_LIMIT_ROLE_LEVEL", Value=409)]
      LEVEL_LIMIT_ROLE_LEVEL = 409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CANNOT_COMPOSITE_GOODS", Value=450)]
      CANNOT_COMPOSITE_GOODS = 450,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_COMPOSITE_STUFF", Value=451)]
      NOT_ENOUGH_COMPOSITE_STUFF = 451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CANNOT_SELL_GOODS", Value=452)]
      CANNOT_SELL_GOODS = 452,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CANNOT_USE_GOODS", Value=453)]
      CANNOT_USE_GOODS = 453,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CANNOT_DECOMPOSE_GOODS", Value=454)]
      CANNOT_DECOMPOSE_GOODS = 454,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REACHED_MAX_STACK_NUM", Value=455)]
      REACHED_MAX_STACK_NUM = 455,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STR_ENHANCE_LESS_GOLD", Value=456)]
      STR_ENHANCE_LESS_GOLD = 456,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_SLOT_LOCK", Value=470)]
      SKILL_SLOT_LOCK = 470,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_SLOT_UNLOCK", Value=471)]
      SKILL_SLOT_UNLOCK = 471,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_SLOT_FILLED", Value=472)]
      SKILL_SLOT_FILLED = 472,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_SLOT_UNFILLED", Value=473)]
      SKILL_SLOT_UNFILLED = 473,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_EQUIPED", Value=474)]
      SKILL_EQUIPED = 474,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_UNEQUIPED", Value=475)]
      SKILL_UNEQUIPED = 475,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_SKILL_UP_STUFF", Value=476)]
      NOT_ENOUGH_SKILL_UP_STUFF = 476,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_ATTR_VALUE", Value=477)]
      NOT_ENOUGH_ATTR_VALUE = 477,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS_EQUIPED", Value=480)]
      GOODS_EQUIPED = 480,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS_UNEQUIPED", Value=481)]
      GOODS_UNEQUIPED = 481,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS_SLOT_UNFILLED", Value=482)]
      GOODS_SLOT_UNFILLED = 482,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL_LIMIT_GOODS_LEVEL", Value=483)]
      LEVEL_LIMIT_GOODS_LEVEL = 483,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIPMENT_POSITION_NOT_MATCH", Value=484)]
      EQUIPMENT_POSITION_NOT_MATCH = 484,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_HAVE_EQUIPMENT", Value=485)]
      NOT_HAVE_EQUIPMENT = 485,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIPMENT_NOT_ENOUGH_MONTY", Value=487)]
      EQUIPMENT_NOT_ENOUGH_MONTY = 487,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIPMENT_NOT_EXIST", Value=488)]
      EQUIPMENT_NOT_EXIST = 488,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS_REACH_MAX", Value=489)]
      GOODS_REACH_MAX = 489,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STORE_GOODS_SELL_OUT", Value=490)]
      STORE_GOODS_SELL_OUT = 490,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_TIME_USE_UP", Value=491)]
      BUY_TIME_USE_UP = 491,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMAIN_CHALLENGE_TIMES", Value=492)]
      REMAIN_CHALLENGE_TIMES = 492,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_MATCHED", Value=500)]
      ALREADY_MATCHED = 500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_ROLES", Value=501)]
      NOT_ENOUGH_ROLES = 501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_PVP", Value=502)]
      ALREADY_PVP = 502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WAIT_ALL_PLAYER_READY", Value=503)]
      WAIT_ALL_PLAYER_READY = 503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REACH_FRIENDS_MAX", Value=510)]
      REACH_FRIENDS_MAX = 510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REACH_BLACK_LIST_MAX", Value=511)]
      REACH_BLACK_LIST_MAX = 511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REACH_FRIEND_PRESENT_MAX", Value=512)]
      REACH_FRIEND_PRESENT_MAX = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REACH_FRIEND_GET_GIFT_MAX", Value=513)]
      REACH_FRIEND_GET_GIFT_MAX = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_PRESEND_FRIEND", Value=514)]
      ALREADY_PRESEND_FRIEND = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_GET_GIFT_FRIEND", Value=515)]
      ALREADY_GET_GIFT_FRIEND = 515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TARGET_NOT_FRIEND", Value=516)]
      TARGET_NOT_FRIEND = 516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TARGET_NOT_BLACKLIST", Value=517)]
      TARGET_NOT_BLACKLIST = 517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TARGET_IN_BLACKLIST", Value=518)]
      TARGET_IN_BLACKLIST = 518,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TARGET_IN_FRIENDS", Value=519)]
      TARGET_IN_FRIENDS = 519,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TARGET_IS_NOT_EXIST", Value=520)]
      TARGET_IS_NOT_EXIST = 520,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_FRIEND_CAN_PRESENT", Value=521)]
      NOT_FRIEND_CAN_PRESENT = 521,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TARGET_IN_SEND_APPLY", Value=522)]
      TARGET_IN_SEND_APPLY = 522,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND_OFFLINE", Value=530)]
      FRIEND_OFFLINE = 530,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND_IN_MATCH", Value=531)]
      FRIEND_IN_MATCH = 531,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_OUT_DUE", Value=532)]
      INVITE_OUT_DUE = 532,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MASTER_EXIT", Value=533)]
      MASTER_EXIT = 533,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTTEN_OFFLINE", Value=534)]
      PARTTEN_OFFLINE = 534,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND_IN_ROOM", Value=535)]
      FRIEND_IN_ROOM = 535,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM_FULL", Value=536)]
      ROOM_FULL = 536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_START_MATCHING", Value=537)]
      ALREADY_START_MATCHING = 537,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_INVITE_FRIEND", Value=538)]
      ALREADY_INVITE_FRIEND = 538,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_REACH_MAX", Value=539)]
      INVITE_REACH_MAX = 539,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IN_COOLING", Value=550)]
      IN_COOLING = 550,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL_LIMIT_TRAINING", Value=551)]
      LEVEL_LIMIT_TRAINING = 551,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REACH_MAX_COUNT_TRAINING", Value=552)]
      REACH_MAX_COUNT_TRAINING = 552,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STR_EXERCIE_LESS_GOLD", Value=553)]
      STR_EXERCIE_LESS_GOLD = 553,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_MAIL_ATTACHMENT_FAILED", Value=600)]
      GET_MAIL_ATTACHMENT_FAILED = 600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_HP_ERROR_TIME", Value=610)]
      GET_HP_ERROR_TIME = 610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPEATED_GET_HP", Value=611)]
      REPEATED_GET_HP = 611,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REACH_MAX_RESET_TIMES", Value=650)]
      REACH_MAX_RESET_TIMES = 650,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEED_GET_THROUGH_FIRST", Value=651)]
      NEED_GET_THROUGH_FIRST = 651,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER_AWARDS_CAN_GET", Value=660)]
      OTHER_AWARDS_CAN_GET = 660,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUNCTION_CLOSED", Value=661)]
      FUNCTION_CLOSED = 661,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AWARDS_GETED", Value=662)]
      AWARDS_GETED = 662,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DO_NOT_GET_AWARDS", Value=663)]
      DO_NOT_GET_AWARDS = 663,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TASK_CONDITION_UNFINISHED", Value=680)]
      TASK_CONDITION_UNFINISHED = 680,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUIDE_CONDITION_UNFINISHED", Value=681)]
      GUIDE_CONDITION_UNFINISHED = 681,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS_OUT_OF_DATE", Value=700)]
      GOODS_OUT_OF_DATE = 700,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FASHION_NOT_MATCH_SHAPE", Value=701)]
      FASHION_NOT_MATCH_SHAPE = 701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENDER_NOT_MATCH", Value=702)]
      GENDER_NOT_MATCH = 702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_OWN_THIS_FASHION", Value=703)]
      NOT_OWN_THIS_FASHION = 703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_REACH_CONDITION", Value=720)]
      NOT_REACH_CONDITION = 720,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_IN_MATCH_QUEUE", Value=760)]
      NOT_IN_MATCH_QUEUE = 760,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_TIME_OUT", Value=761)]
      GAME_TIME_OUT = 761,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUALIFYING_COOL", Value=770)]
      QUALIFYING_COOL = 770,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIVAL_BATTLEING", Value=771)]
      RIVAL_BATTLEING = 771,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANKING_CHANGE", Value=772)]
      RANKING_CHANGE = 772,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BE_CHALLENGEED_IN", Value=773)]
      BE_CHALLENGEED_IN = 773,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_NOT_OPEN", Value=780)]
      GAME_NOT_OPEN = 780,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_CLOSE", Value=781)]
      ACTIVITY_CLOSE = 781,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_OPEN_CARD_TIMES", Value=785)]
      NOT_ENOUGH_OPEN_CARD_TIMES = 785,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRACTICE_COOL", Value=790)]
      PRACTICE_COOL = 790,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORLD_CHANNEL_COOL", Value=791)]
      WORLD_CHANNEL_COOL = 791,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_LOTTERY_TIMES", Value=800)]
      NOT_ENOUGH_LOTTERY_TIMES = 800,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD_LOTTERY_AWARD_FAILED", Value=801)]
      ADD_LOTTERY_AWARD_FAILED = 801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BADGE_BOOK_NUM_REACH_MAX", Value=820)]
      BADGE_BOOK_NUM_REACH_MAX = 820,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNLOCK_BADGE_SLOT_IN_ORDER", Value=821)]
      UNLOCK_BADGE_SLOT_IN_ORDER = 821,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_UNLOCK_BADGE_SLOT", Value=822)]
      NO_UNLOCK_BADGE_SLOT = 822,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_BADGE", Value=823)]
      NO_ENOUGH_BADGE = 823,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAN_NOT_UNLOCK_IN_ADVANCE", Value=824)]
      CAN_NOT_UNLOCK_IN_ADVANCE = 824,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_CAN_DECOMPOSE_BADGE", Value=825)]
      NO_CAN_DECOMPOSE_BADGE = 825,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_OPERATION", Value=900)]
      INVALID_OPERATION = 900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CONFIGURATION", Value=920)]
      ERROR_CONFIGURATION = 920,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CHEAT", Value=950)]
      ERROR_CHEAT = 950,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_IN_CHAT_ROOM", Value=970)]
      NO_IN_CHAT_ROOM = 970,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW_ERROR", Value=99999)]
      UNKNOW_ERROR = 99999
    }
  
}