//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Friend.proto
// Note: requires additional types generated from: Role.proto
// Note: requires additional types generated from: Player.proto
// Note: requires additional types generated from: QualifyingNewer.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendInfo")]
  public partial class FriendInfo : global::ProtoBuf.IExtensible
  {
    public FriendInfo() {}
    
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _plat_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"plat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint plat_id
    {
      get { return _plat_id; }
      set { _plat_id = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _vip_level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private uint _present_flag = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"present_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint present_flag
    {
      get { return _present_flag; }
      set { _present_flag = value; }
    }
    private uint _get_flag = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"get_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_flag
    {
      get { return _get_flag; }
      set { _get_flag = value; }
    }
    private uint _online = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint online
    {
      get { return _online; }
      set { _online = value; }
    }
    private uint _logout_time = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"logout_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint logout_time
    {
      get { return _logout_time; }
      set { _logout_time = value; }
    }
    private uint _shinwakan = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"shinwakan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shinwakan
    {
      get { return _shinwakan; }
      set { _shinwakan = value; }
    }
    private uint _pvp_ladder_score = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pvp_ladder_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pvp_ladder_score
    {
      get { return _pvp_ladder_score; }
      set { _pvp_ladder_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendListInfo")]
  public partial class FriendListInfo : global::ProtoBuf.IExtensible
  {
    public FriendListInfo() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _friends = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> friends
    {
      get { return _friends; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _apply_list = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"apply_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> apply_list
    {
      get { return _apply_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _black_list = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"black_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> black_list
    {
      get { return _black_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _gift_list = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"gift_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> gift_list
    {
      get { return _gift_list; }
    }
  
    private uint _present_times = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"present_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint present_times
    {
      get { return _present_times; }
      set { _present_times = value; }
    }
    private uint _get_gift_times = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"get_gift_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_gift_times
    {
      get { return _get_gift_times; }
      set { _get_gift_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyFriendInfo")]
  public partial class NotifyFriendInfo : global::ProtoBuf.IExtensible
  {
    public NotifyFriendInfo() {}
    
    private fogs.proto.msg.FriendListInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fogs.proto.msg.FriendListInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendOperationReq")]
  public partial class FriendOperationReq : global::ProtoBuf.IExtensible
  {
    public FriendOperationReq() {}
    
    private fogs.proto.msg.FriendOperationType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.FriendOperationType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _friend = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> friend
    {
      get { return _friend; }
    }
  
    private uint _all_flag = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"all_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint all_flag
    {
      get { return _all_flag; }
      set { _all_flag = value; }
    }
    private fogs.proto.msg.FriendInfo _op_friend = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"op_friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.FriendInfo op_friend
    {
      get { return _op_friend; }
      set { _op_friend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendOperationResp")]
  public partial class FriendOperationResp : global::ProtoBuf.IExtensible
  {
    public FriendOperationResp() {}
    
    private fogs.proto.msg.FriendOperationType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.FriendOperationType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _friend = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> friend
    {
      get { return _friend; }
    }
  
    private fogs.proto.msg.FriendInfo _op_friend = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"op_friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.FriendInfo op_friend
    {
      get { return _op_friend; }
      set { _op_friend = value; }
    }
    private uint _present_times = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"present_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint present_times
    {
      get { return _present_times; }
      set { _present_times = value; }
    }
    private uint _get_gift_times = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"get_gift_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_gift_times
    {
      get { return _get_gift_times; }
      set { _get_gift_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryFriendInfoReq")]
  public partial class QueryFriendInfoReq : global::ProtoBuf.IExtensible
  {
    public QueryFriendInfoReq() {}
    
    private fogs.proto.msg.FriendInfo _friend;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fogs.proto.msg.FriendInfo friend
    {
      get { return _friend; }
      set { _friend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryFriendInfoResp")]
  public partial class QueryFriendInfoResp : global::ProtoBuf.IExtensible
  {
    public QueryFriendInfoResp() {}
    
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _vip_level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private fogs.proto.msg.PvpRegularInfo _regular = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"regular", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PvpRegularInfo regular
    {
      get { return _regular; }
      set { _regular = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.RoleMatchResData> _role_data = new global::System.Collections.Generic.List<fogs.proto.msg.RoleMatchResData>();
    [global::ProtoBuf.ProtoMember(7, Name=@"role_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.RoleMatchResData> role_data
    {
      get { return _role_data; }
    }
  
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _role_count = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"role_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_count
    {
      get { return _role_count; }
      set { _role_count = value; }
    }
    private uint _fashion_count = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"fashion_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashion_count
    {
      get { return _fashion_count; }
      set { _fashion_count = value; }
    }
    private string _guild_name = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"guild_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guild_name
    {
      get { return _guild_name; }
      set { _guild_name = value; }
    }
    private string _team_name = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"team_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string team_name
    {
      get { return _team_name; }
      set { _team_name = value; }
    }
    private fogs.proto.msg.QualifyingNewInfo _qualifying_new = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"qualifying_new", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.QualifyingNewInfo qualifying_new
    {
      get { return _qualifying_new; }
      set { _qualifying_new = value; }
    }
    private fogs.proto.msg.PvpLadderInfo _pvp_ladder = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"pvp_ladder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PvpLadderInfo pvp_ladder
    {
      get { return _pvp_ladder; }
      set { _pvp_ladder = value; }
    }
    private uint _pvp_ladder_score = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"pvp_ladder_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pvp_ladder_score
    {
      get { return _pvp_ladder_score; }
      set { _pvp_ladder_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleMatchResData")]
  public partial class RoleMatchResData : global::ProtoBuf.IExtensible
  {
    public RoleMatchResData() {}
    
    private uint _win_times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint win_times
    {
      get { return _win_times; }
      set { _win_times = value; }
    }
    private uint _race_times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"race_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint race_times
    {
      get { return _race_times; }
      set { _race_times = value; }
    }
    private uint _role_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePlayerInfo")]
  public partial class UpdatePlayerInfo : global::ProtoBuf.IExtensible
  {
    public UpdatePlayerInfo() {}
    
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _vip_level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private uint _plat_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"plat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint plat_id
    {
      get { return _plat_id; }
      set { _plat_id = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.RoleMatchResData> _role_data = new global::System.Collections.Generic.List<fogs.proto.msg.RoleMatchResData>();
    [global::ProtoBuf.ProtoMember(7, Name=@"role_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.RoleMatchResData> role_data
    {
      get { return _role_data; }
    }
  
    private fogs.proto.msg.PvpRegularInfo _regular = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"regular", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PvpRegularInfo regular
    {
      get { return _regular; }
      set { _regular = value; }
    }
    private uint _flag = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private uint _logout_time = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"logout_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint logout_time
    {
      get { return _logout_time; }
      set { _logout_time = value; }
    }
    private uint _role_count = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"role_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_count
    {
      get { return _role_count; }
      set { _role_count = value; }
    }
    private uint _fashion_count = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"fashion_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashion_count
    {
      get { return _fashion_count; }
      set { _fashion_count = value; }
    }
    private string _guild_name = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"guild_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guild_name
    {
      get { return _guild_name; }
      set { _guild_name = value; }
    }
    private string _team_name = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"team_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string team_name
    {
      get { return _team_name; }
      set { _team_name = value; }
    }
    private fogs.proto.msg.QualifyingNewInfo _qualifying_new = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"qualifying_new", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.QualifyingNewInfo qualifying_new
    {
      get { return _qualifying_new; }
      set { _qualifying_new = value; }
    }
    private fogs.proto.msg.PvpLadderInfo _pvp_ladder = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"pvp_ladder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PvpLadderInfo pvp_ladder
    {
      get { return _pvp_ladder; }
      set { _pvp_ladder = value; }
    }
    private uint _pvp_ladder_score = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"pvp_ladder_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pvp_ladder_score
    {
      get { return _pvp_ladder_score; }
      set { _pvp_ladder_score = value; }
    }
    private uint _silent_start_time = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"silent_start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint silent_start_time
    {
      get { return _silent_start_time; }
      set { _silent_start_time = value; }
    }
    private uint _silent_duration = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"silent_duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint silent_duration
    {
      get { return _silent_duration; }
      set { _silent_duration = value; }
    }
    private string _acc_name = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"acc_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string acc_name
    {
      get { return _acc_name; }
      set { _acc_name = value; }
    }
    private fogs.proto.msg.QualifyingNewerInfo _qualifying_newer = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"qualifying_newer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.QualifyingNewerInfo qualifying_newer
    {
      get { return _qualifying_newer; }
      set { _qualifying_newer = value; }
    }
    private uint _qualifying_newer_score = default(uint);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"qualifying_newer_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_newer_score
    {
      get { return _qualifying_newer_score; }
      set { _qualifying_newer_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyOffLineInfoToPlayer")]
  public partial class NotifyOffLineInfoToPlayer : global::ProtoBuf.IExtensible
  {
    public NotifyOffLineInfoToPlayer() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _gift_list = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gift_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> gift_list
    {
      get { return _gift_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _apply_list = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"apply_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> apply_list
    {
      get { return _apply_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchFriend")]
  public partial class SearchFriend : global::ProtoBuf.IExtensible
  {
    public SearchFriend() {}
    
    private fogs.proto.msg.SearchFriendType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SearchFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchFriendResp")]
  public partial class SearchFriendResp : global::ProtoBuf.IExtensible
  {
    public SearchFriendResp() {}
    
    private fogs.proto.msg.SearchFriendType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SearchFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> _info = new global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.FriendInfo> info
    {
      get { return _info; }
    }
  
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"FriendOperationType")]
    public enum FriendOperationType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_PRESEND", Value=1)]
      FOT_PRESEND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_ADD", Value=2)]
      FOT_ADD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_BLACK", Value=3)]
      FOT_BLACK = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_GETAWARDS", Value=4)]
      FOT_GETAWARDS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_QUERY", Value=5)]
      FOT_QUERY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_AGREE_APPLY", Value=6)]
      FOT_AGREE_APPLY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_APPLY", Value=7)]
      FOT_APPLY = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_DEL_FRIEND", Value=8)]
      FOT_DEL_FRIEND = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_DEL_BLACK", Value=9)]
      FOT_DEL_BLACK = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_QUERY_BLACK", Value=10)]
      FOT_QUERY_BLACK = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_QUERY_APPLY", Value=11)]
      FOT_QUERY_APPLY = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_QUERY_GIFT", Value=12)]
      FOT_QUERY_GIFT = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOT_IGNORE_APPLY", Value=13)]
      FOT_IGNORE_APPLY = 13
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SearchFriendType")]
    public enum SearchFriendType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SFT_PRECISE", Value=1)]
      SFT_PRECISE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SFT_CHANGE", Value=2)]
      SFT_CHANGE = 2
    }
  
}