//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Goods.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoodsProto")]
  public partial class GoodsProto : global::ProtoBuf.IExtensible
  {
    public GoodsProto() {}
    
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private fogs.proto.msg.GoodsQuality _quality = fogs.proto.msg.GoodsQuality.GQ_NONE;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.GoodsQuality.GQ_NONE)]
    public fogs.proto.msg.GoodsQuality quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private uint _is_equip = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_equip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint is_equip
    {
      get { return _is_equip; }
      set { _is_equip = value; }
    }
    private uint _time_left = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"time_left", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time_left
    {
      get { return _time_left; }
      set { _time_left = value; }
    }
    private uint _is_used = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"is_used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint is_used
    {
      get { return _is_used; }
      set { _is_used = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _fashion_attr_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"fashion_attr_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> fashion_attr_id
    {
      get { return _fashion_attr_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoodsList")]
  public partial class GoodsList : global::ProtoBuf.IExtensible
  {
    public GoodsList() {}
    
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.GoodsProto> _item = new global::System.Collections.Generic.List<fogs.proto.msg.GoodsProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.GoodsProto> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateGoodsInfo")]
  public partial class UpdateGoodsInfo : global::ProtoBuf.IExtensible
  {
    public UpdateGoodsInfo() {}
    
    private fogs.proto.msg.GoodsUpdateType _type = fogs.proto.msg.GoodsUpdateType.GUT_NEW;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.GoodsUpdateType.GUT_NEW)]
    public fogs.proto.msg.GoodsUpdateType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private fogs.proto.msg.GoodsProto _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.GoodsProto data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateGoods")]
  public partial class UpdateGoods : global::ProtoBuf.IExtensible
  {
    public UpdateGoods() {}
    
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.UpdateGoodsInfo> _goods_list = new global::System.Collections.Generic.List<fogs.proto.msg.UpdateGoodsInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"goods_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.UpdateGoodsInfo> goods_list
    {
      get { return _goods_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoodsInfo")]
  public partial class GoodsInfo : global::ProtoBuf.IExtensible
  {
    public GoodsInfo() {}
    
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellGoods")]
  public partial class SellGoods : global::ProtoBuf.IExtensible
  {
    public SellGoods() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.GoodsInfo> _info = new global::System.Collections.Generic.List<fogs.proto.msg.GoodsInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.GoodsInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellGoodsResp")]
  public partial class SellGoodsResp : global::ProtoBuf.IExtensible
  {
    public SellGoodsResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.GoodsInfo> _info = new global::System.Collections.Generic.List<fogs.proto.msg.GoodsInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.GoodsInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseGoods")]
  public partial class UseGoods : global::ProtoBuf.IExtensible
  {
    public UseGoods() {}
    
    private ulong _uuid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _target = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint target
    {
      get { return _target; }
      set { _target = value; }
    }
    private uint _exp_card = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"exp_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp_card
    {
      get { return _exp_card; }
      set { _exp_card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseGoodsResp")]
  public partial class UseGoodsResp : global::ProtoBuf.IExtensible
  {
    public UseGoodsResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _uuid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _target = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint target
    {
      get { return _target; }
      set { _target = value; }
    }
    private uint _target_exp = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"target_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint target_exp
    {
      get { return _target_exp; }
      set { _target_exp = value; }
    }
    private uint _target_level = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"target_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint target_level
    {
      get { return _target_level; }
      set { _target_level = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData> _awards = new global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData>();
    [global::ProtoBuf.ProtoMember(9, Name=@"awards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData> awards
    {
      get { return _awards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompositeGoods")]
  public partial class CompositeGoods : global::ProtoBuf.IExtensible
  {
    public CompositeGoods() {}
    
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompositeGoodsResp")]
  public partial class CompositeGoodsResp : global::ProtoBuf.IExtensible
  {
    public CompositeGoodsResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecomposeGoods")]
  public partial class DecomposeGoods : global::ProtoBuf.IExtensible
  {
    public DecomposeGoods() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _uuid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> uuid
    {
      get { return _uuid; }
    }
  
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecomposeGoodsResp")]
  public partial class DecomposeGoodsResp : global::ProtoBuf.IExtensible
  {
    public DecomposeGoodsResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private fogs.proto.msg.GoodsCategory _category;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GoodsCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FashionResetAttrReq")]
  public partial class FashionResetAttrReq : global::ProtoBuf.IExtensible
  {
    public FashionResetAttrReq() {}
    
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FashionResetAttrResp")]
  public partial class FashionResetAttrResp : global::ProtoBuf.IExtensible
  {
    public FashionResetAttrResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GoodsCategory")]
    public enum GoodsCategory
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_NONE", Value=0)]
      GC_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_RESOURCE", Value=1)]
      GC_RESOURCE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_SKILL", Value=2)]
      GC_SKILL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_FAVORITE", Value=3)]
      GC_FAVORITE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_CONSUME", Value=4)]
      GC_CONSUME = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_EQUIPMENT", Value=5)]
      GC_EQUIPMENT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_FASHION", Value=6)]
      GC_FASHION = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_EXERCISE", Value=7)]
      GC_EXERCISE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_MATERIAL", Value=8)]
      GC_MATERIAL = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_ROLE", Value=9)]
      GC_ROLE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_BADGE", Value=10)]
      GC_BADGE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GC_TOTAL", Value=20)]
      GC_TOTAL = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GoodsSubCategory")]
    public enum GoodsSubCategory
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_NONE", Value=0)]
      GSC_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_1", Value=1)]
      GSC_1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_2", Value=2)]
      GSC_2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_3", Value=3)]
      GSC_3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_4", Value=4)]
      GSC_4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_5", Value=5)]
      GSC_5 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_6", Value=6)]
      GSC_6 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_7", Value=7)]
      GSC_7 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_BADGE_PAINT", Value=8)]
      GSC_BADGE_PAINT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSC_TOTAL", Value=100)]
      GSC_TOTAL = 100
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GoodsQuality")]
    public enum GoodsQuality
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GQ_NONE", Value=0)]
      GQ_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GQ_WHITE", Value=1)]
      GQ_WHITE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GQ_GREEN", Value=2)]
      GQ_GREEN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GQ_BLUE", Value=3)]
      GQ_BLUE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GQ_PURPEL", Value=4)]
      GQ_PURPEL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GQ_GOLDEN", Value=5)]
      GQ_GOLDEN = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GoodsUpdateType")]
    public enum GoodsUpdateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUT_NEW", Value=1)]
      GUT_NEW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUT_UPDATE", Value=2)]
      GUT_UPDATE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUT_DELETE", Value=3)]
      GUT_DELETE = 3
    }
  
}