//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Server.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HandshakeRequest")]
  public partial class HandshakeRequest : global::ProtoBuf.IExtensible
  {
    public HandshakeRequest() {}
    
    private uint _server_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private string _extern_ip = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"extern_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extern_ip
    {
      get { return _extern_ip; }
      set { _extern_ip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HandshakeResponse")]
  public partial class HandshakeResponse : global::ProtoBuf.IExtensible
  {
    public HandshakeResponse() {}
    
    private uint _server_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private uint _boot_time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"boot_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint boot_time
    {
      get { return _boot_time; }
      set { _boot_time = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReloadLuaFile")]
  public partial class ReloadLuaFile : global::ProtoBuf.IExtensible
  {
    public ReloadLuaFile() {}
    
    private readonly global::System.Collections.Generic.List<string> _lua_file = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"lua_file", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> lua_file
    {
      get { return _lua_file; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportServerLoad")]
  public partial class ReportServerLoad : global::ProtoBuf.IExtensible
  {
    public ReportServerLoad() {}
    
    private uint _server_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private string _gateway_ip;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gateway_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gateway_ip
    {
      get { return _gateway_ip; }
      set { _gateway_ip = value; }
    }
    private uint _gateway_port;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gateway_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gateway_port
    {
      get { return _gateway_port; }
      set { _gateway_port = value; }
    }
    private uint _load_info;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"load_info", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint load_info
    {
      get { return _load_info; }
      set { _load_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerDiscontinueInfo")]
  public partial class ServerDiscontinueInfo : global::ProtoBuf.IExtensible
  {
    public ServerDiscontinueInfo() {}
    
    private uint _server_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_type
    {
      get { return _server_type; }
      set { _server_type = value; }
    }
    private uint _server_index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_index
    {
      get { return _server_index; }
      set { _server_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Heartbeat")]
  public partial class Heartbeat : global::ProtoBuf.IExtensible
  {
    public Heartbeat() {}
    
    private double _server_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnNewDayCome")]
  public partial class OnNewDayCome : global::ProtoBuf.IExtensible
  {
    public OnNewDayCome() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NoticeToClient")]
  public partial class NoticeToClient : global::ProtoBuf.IExtensible
  {
    public NoticeToClient() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}