//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Shoot.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartShoot")]
  public partial class StartShoot : global::ProtoBuf.IExtensible
  {
    public StartShoot() {}
    
    private uint _diffictly = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"diffictly", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diffictly
    {
      get { return _diffictly; }
      set { _diffictly = value; }
    }
    private fogs.proto.msg.FightRoleInfo _fight_list = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fight_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.FightRoleInfo fight_list
    {
      get { return _fight_list; }
      set { _fight_list = value; }
    }
    private fogs.proto.msg.GameMode _game_mode = fogs.proto.msg.GameMode.GM_None;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"game_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.GameMode.GM_None)]
    public fogs.proto.msg.GameMode game_mode
    {
      get { return _game_mode; }
      set { _game_mode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartShootResp")]
  public partial class StartShootResp : global::ProtoBuf.IExtensible
  {
    public StartShootResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _session_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndShoot")]
  public partial class EndShoot : global::ProtoBuf.IExtensible
  {
    public EndShoot() {}
    
    private ulong _session_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private uint _main_role_side = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"main_role_side", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint main_role_side
    {
      get { return _main_role_side; }
      set { _main_role_side = value; }
    }
    private uint _score_home = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"score_home", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint score_home
    {
      get { return _score_home; }
      set { _score_home = value; }
    }
    private uint _score_away = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"score_away", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint score_away
    {
      get { return _score_away; }
      set { _score_away = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndShootResp")]
  public partial class EndShootResp : global::ProtoBuf.IExtensible
  {
    public EndShootResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData> _awards = new global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"awards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData> awards
    {
      get { return _awards; }
    }
  
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private fogs.proto.msg.GameMode _game_mode = fogs.proto.msg.GameMode.GM_None;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"game_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.GameMode.GM_None)]
    public fogs.proto.msg.GameMode game_mode
    {
      get { return _game_mode; }
      set { _game_mode = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.MatchRoleInfo> _info = new global::System.Collections.Generic.List<fogs.proto.msg.MatchRoleInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.MatchRoleInfo> info
    {
      get { return _info; }
    }
  
    private uint _awards_times = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"awards_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint awards_times
    {
      get { return _awards_times; }
      set { _awards_times = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData> _diamond_awards = new global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData>();
    [global::ProtoBuf.ProtoMember(7, Name=@"diamond_awards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.KeyValueData> diamond_awards
    {
      get { return _diamond_awards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShootOpenReq")]
  public partial class ShootOpenReq : global::ProtoBuf.IExtensible
  {
    public ShootOpenReq() {}
    
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameModeInfo")]
  public partial class GameModeInfo : global::ProtoBuf.IExtensible
  {
    public GameModeInfo() {}
    
    private fogs.proto.msg.GameMode _game_mode = fogs.proto.msg.GameMode.GM_None;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"game_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.GameMode.GM_None)]
    public fogs.proto.msg.GameMode game_mode
    {
      get { return _game_mode; }
      set { _game_mode = value; }
    }
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private uint _npc = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"npc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint npc
    {
      get { return _npc; }
      set { _npc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShootOpenResp")]
  public partial class ShootOpenResp : global::ProtoBuf.IExtensible
  {
    public ShootOpenResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.GameModeInfo> _game_mode_info = new global::System.Collections.Generic.List<fogs.proto.msg.GameModeInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"game_mode_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.GameModeInfo> game_mode_info
    {
      get { return _game_mode_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShootBuyTimesReq")]
  public partial class ShootBuyTimesReq : global::ProtoBuf.IExtensible
  {
    public ShootBuyTimesReq() {}
    
    private fogs.proto.msg.GameMode _game_mode = fogs.proto.msg.GameMode.GM_None;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"game_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.GameMode.GM_None)]
    public fogs.proto.msg.GameMode game_mode
    {
      get { return _game_mode; }
      set { _game_mode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShootBuyTimesResp")]
  public partial class ShootBuyTimesResp : global::ProtoBuf.IExtensible
  {
    public ShootBuyTimesResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShootOpenCardReq")]
  public partial class ShootOpenCardReq : global::ProtoBuf.IExtensible
  {
    public ShootOpenCardReq() {}
    
    private fogs.proto.msg.ShootDiamondTurnCardType _type = fogs.proto.msg.ShootDiamondTurnCardType.SDTCT_NONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.ShootDiamondTurnCardType.SDTCT_NONE)]
    public fogs.proto.msg.ShootDiamondTurnCardType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShootOpendCardResp")]
  public partial class ShootOpendCardResp : global::ProtoBuf.IExtensible
  {
    public ShootOpendCardResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private fogs.proto.msg.KeyValueData _awards = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"awards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.KeyValueData awards
    {
      get { return _awards; }
      set { _awards = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.MatchRoleInfo> _info = new global::System.Collections.Generic.List<fogs.proto.msg.MatchRoleInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.MatchRoleInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}