//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Skill.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillSlotProto")]
  public partial class SkillSlotProto : global::ProtoBuf.IExtensible
  {
    public SkillSlotProto() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _is_unlock = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_unlock", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint is_unlock
    {
      get { return _is_unlock; }
      set { _is_unlock = value; }
    }
    private ulong _skill_uuid = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skill_uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong skill_uuid
    {
      get { return _skill_uuid; }
      set { _skill_uuid = value; }
    }
    private uint _skill_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private uint _skill_level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skill_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_level
    {
      get { return _skill_level; }
      set { _skill_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillOperation")]
  public partial class SkillOperation : global::ProtoBuf.IExtensible
  {
    public SkillOperation() {}
    
    private fogs.proto.msg.SkillOperationType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SkillOperationType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ulong _skill_uuid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skill_uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong skill_uuid
    {
      get { return _skill_uuid; }
      set { _skill_uuid = value; }
    }
    private uint _role_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private uint _slot_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillOperationResp")]
  public partial class SkillOperationResp : global::ProtoBuf.IExtensible
  {
    public SkillOperationResp() {}
    
    private fogs.proto.msg.SkillOperationType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SkillOperationType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _skill_uuid = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skill_uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong skill_uuid
    {
      get { return _skill_uuid; }
      set { _skill_uuid = value; }
    }
    private uint _skill_level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skill_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_level
    {
      get { return _skill_level; }
      set { _skill_level = value; }
    }
    private uint _role_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private uint _slot_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Skill")]
  public partial class Skill : global::ProtoBuf.IExtensible
  {
    public Skill() {}
    
    private uint _skill_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private uint _action_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"action_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint action_id
    {
      get { return _action_id; }
      set { _action_id = value; }
    }
    private int _skill_matchedKeyIdx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skill_matchedKeyIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_matchedKeyIdx
    {
      get { return _skill_matchedKeyIdx; }
      set { _skill_matchedKeyIdx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SkillOperationType")]
    public enum SkillOperationType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOT_UNLOCK_SLOT", Value=1)]
      SOT_UNLOCK_SLOT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOT_EQUIP", Value=2)]
      SOT_EQUIP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOT_UNEQUIP", Value=3)]
      SOT_UNEQUIP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOT_UPGRADE", Value=4)]
      SOT_UPGRADE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOT_USE", Value=5)]
      SOT_USE = 5
    }
  
}