//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Task.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskConditionMain")]
  public partial class TaskConditionMain : global::ProtoBuf.IExtensible
  {
    public TaskConditionMain() {}
    
    private uint _gold_reach = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gold_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold_reach
    {
      get { return _gold_reach; }
      set { _gold_reach = value; }
    }
    private uint _honor_reach = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"honor_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint honor_reach
    {
      get { return _honor_reach; }
      set { _honor_reach = value; }
    }
    private uint _diamond_earned_reach = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"diamond_earned_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond_earned_reach
    {
      get { return _diamond_earned_reach; }
      set { _diamond_earned_reach = value; }
    }
    private uint _regular_winning_streak = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"regular_winning_streak", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regular_winning_streak
    {
      get { return _regular_winning_streak; }
      set { _regular_winning_streak = value; }
    }
    private uint _complete_section = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"complete_section", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint complete_section
    {
      get { return _complete_section; }
      set { _complete_section = value; }
    }
    private uint _team_level_reach = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"team_level_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint team_level_reach
    {
      get { return _team_level_reach; }
      set { _team_level_reach = value; }
    }
    private uint _role_num_reach = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"role_num_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_num_reach
    {
      get { return _role_num_reach; }
      set { _role_num_reach = value; }
    }
    private uint _role_level_reach = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"role_level_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_level_reach
    {
      get { return _role_level_reach; }
      set { _role_level_reach = value; }
    }
    private uint _role_star_reach = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"role_star_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_star_reach
    {
      get { return _role_star_reach; }
      set { _role_star_reach = value; }
    }
    private uint _role_quality_reach = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"role_quality_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_quality_reach
    {
      get { return _role_quality_reach; }
      set { _role_quality_reach = value; }
    }
    private uint _role_talent_reach = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"role_talent_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_talent_reach
    {
      get { return _role_talent_reach; }
      set { _role_talent_reach = value; }
    }
    private uint _role_exercise_reach = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"role_exercise_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_exercise_reach
    {
      get { return _role_exercise_reach; }
      set { _role_exercise_reach = value; }
    }
    private uint _freestyle_level_reach = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"freestyle_level_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint freestyle_level_reach
    {
      get { return _freestyle_level_reach; }
      set { _freestyle_level_reach = value; }
    }
    private uint _skill_level_reach = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"skill_level_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_level_reach
    {
      get { return _skill_level_reach; }
      set { _skill_level_reach = value; }
    }
    private uint _role_opened_skill_slot_reach = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"role_opened_skill_slot_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_opened_skill_slot_reach
    {
      get { return _role_opened_skill_slot_reach; }
      set { _role_opened_skill_slot_reach = value; }
    }
    private uint _regular_win_times_reach = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"regular_win_times_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regular_win_times_reach
    {
      get { return _regular_win_times_reach; }
      set { _regular_win_times_reach = value; }
    }
    private uint _captain_num_reach = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"captain_num_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint captain_num_reach
    {
      get { return _captain_num_reach; }
      set { _captain_num_reach = value; }
    }
    private uint _tattoo_num_reach = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"tattoo_num_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tattoo_num_reach
    {
      get { return _tattoo_num_reach; }
      set { _tattoo_num_reach = value; }
    }
    private uint _tattoo_level_reach = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"tattoo_level_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tattoo_level_reach
    {
      get { return _tattoo_level_reach; }
      set { _tattoo_level_reach = value; }
    }
    private uint _decompose_tattoo_num_reach = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"decompose_tattoo_num_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint decompose_tattoo_num_reach
    {
      get { return _decompose_tattoo_num_reach; }
      set { _decompose_tattoo_num_reach = value; }
    }
    private uint _training_ph_levle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"training_ph_levle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint training_ph_levle_reach
    {
      get { return _training_ph_levle_reach; }
      set { _training_ph_levle_reach = value; }
    }
    private uint _training_strength_levle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"training_strength_levle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint training_strength_levle_reach
    {
      get { return _training_strength_levle_reach; }
      set { _training_strength_levle_reach = value; }
    }
    private uint _training_dunk_levle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"training_dunk_levle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint training_dunk_levle_reach
    {
      get { return _training_dunk_levle_reach; }
      set { _training_dunk_levle_reach = value; }
    }
    private uint _training_layup_levle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"training_layup_levle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint training_layup_levle_reach
    {
      get { return _training_layup_levle_reach; }
      set { _training_layup_levle_reach = value; }
    }
    private uint _training_shoot_levle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"training_shoot_levle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint training_shoot_levle_reach
    {
      get { return _training_shoot_levle_reach; }
      set { _training_shoot_levle_reach = value; }
    }
    private uint _training_defense_levle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"training_defense_levle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint training_defense_levle_reach
    {
      get { return _training_defense_levle_reach; }
      set { _training_defense_levle_reach = value; }
    }
    private uint _training_skill_levle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"training_skill_levle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint training_skill_levle_reach
    {
      get { return _training_skill_levle_reach; }
      set { _training_skill_levle_reach = value; }
    }
    private uint _training_vigour_levle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"training_vigour_levle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint training_vigour_levle_reach
    {
      get { return _training_vigour_levle_reach; }
      set { _training_vigour_levle_reach = value; }
    }
    private uint _qualifying_rank_reach = default(uint);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"qualifying_rank_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_rank_reach
    {
      get { return _qualifying_rank_reach; }
      set { _qualifying_rank_reach = value; }
    }
    private uint _qualifying_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"qualifying_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_win_times
    {
      get { return _qualifying_win_times; }
      set { _qualifying_win_times = value; }
    }
    private uint _base_practice_race = default(uint);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"base_practice_race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint base_practice_race
    {
      get { return _base_practice_race; }
      set { _base_practice_race = value; }
    }
    private uint _shoot_practice_race = default(uint);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"shoot_practice_race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shoot_practice_race
    {
      get { return _shoot_practice_race; }
      set { _shoot_practice_race = value; }
    }
    private uint _layup_dunk_practice_race = default(uint);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"layup_dunk_practice_race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint layup_dunk_practice_race
    {
      get { return _layup_dunk_practice_race; }
      set { _layup_dunk_practice_race = value; }
    }
    private uint _rebound_practice_race = default(uint);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"rebound_practice_race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rebound_practice_race
    {
      get { return _rebound_practice_race; }
      set { _rebound_practice_race = value; }
    }
    private uint _block_practice_race = default(uint);
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"block_practice_race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint block_practice_race
    {
      get { return _block_practice_race; }
      set { _block_practice_race = value; }
    }
    private uint _regular_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"regular_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regular_win_times
    {
      get { return _regular_win_times; }
      set { _regular_win_times = value; }
    }
    private uint _regular_get_score = default(uint);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"regular_get_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regular_get_score
    {
      get { return _regular_get_score; }
      set { _regular_get_score = value; }
    }
    private uint _ladder_reach = default(uint);
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"ladder_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ladder_reach
    {
      get { return _ladder_reach; }
      set { _ladder_reach = value; }
    }
    private uint _ladder_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"ladder_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ladder_win_times
    {
      get { return _ladder_win_times; }
      set { _ladder_win_times = value; }
    }
    private uint _ladder_get_score = default(uint);
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"ladder_get_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ladder_get_score
    {
      get { return _ladder_get_score; }
      set { _ladder_get_score = value; }
    }
    private uint _ladder_get_mvp_times = default(uint);
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"ladder_get_mvp_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ladder_get_mvp_times
    {
      get { return _ladder_get_mvp_times; }
      set { _ladder_get_mvp_times = value; }
    }
    private uint _with_friend_battle = default(uint);
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"with_friend_battle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint with_friend_battle
    {
      get { return _with_friend_battle; }
      set { _with_friend_battle = value; }
    }
    private uint _online_battle_reach = default(uint);
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"online_battle_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint online_battle_reach
    {
      get { return _online_battle_reach; }
      set { _online_battle_reach = value; }
    }
    private uint _online_battle_get_score = default(uint);
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"online_battle_get_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint online_battle_get_score
    {
      get { return _online_battle_get_score; }
      set { _online_battle_get_score = value; }
    }
    private uint _full_star_complete_section = default(uint);
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"full_star_complete_section", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint full_star_complete_section
    {
      get { return _full_star_complete_section; }
      set { _full_star_complete_section = value; }
    }
    private uint _badge_number_reach = default(uint);
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"badge_number_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint badge_number_reach
    {
      get { return _badge_number_reach; }
      set { _badge_number_reach = value; }
    }
    private uint _badge_level_number_reach = default(uint);
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"badge_level_number_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint badge_level_number_reach
    {
      get { return _badge_level_number_reach; }
      set { _badge_level_number_reach = value; }
    }
    private uint _with_friend_qualifying_newer_times = default(uint);
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"with_friend_qualifying_newer_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint with_friend_qualifying_newer_times
    {
      get { return _with_friend_qualifying_newer_times; }
      set { _with_friend_qualifying_newer_times = value; }
    }
    private uint _qualifying_newer_reach = default(uint);
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"qualifying_newer_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_newer_reach
    {
      get { return _qualifying_newer_reach; }
      set { _qualifying_newer_reach = value; }
    }
    private uint _qualifying_newer_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"qualifying_newer_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_newer_win_times
    {
      get { return _qualifying_newer_win_times; }
      set { _qualifying_newer_win_times = value; }
    }
    private uint _qualifying_newer_get_sorce = default(uint);
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"qualifying_newer_get_sorce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_newer_get_sorce
    {
      get { return _qualifying_newer_get_sorce; }
      set { _qualifying_newer_get_sorce = value; }
    }
    private uint _qualifying_newer_mvp_times = default(uint);
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"qualifying_newer_mvp_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_newer_mvp_times
    {
      get { return _qualifying_newer_mvp_times; }
      set { _qualifying_newer_mvp_times = value; }
    }
    private uint _qualifying_new_reach_mvp_times = default(uint);
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"qualifying_new_reach_mvp_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_new_reach_mvp_times
    {
      get { return _qualifying_new_reach_mvp_times; }
      set { _qualifying_new_reach_mvp_times = value; }
    }
    private uint _qualifying_new_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"qualifying_new_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_new_win_times
    {
      get { return _qualifying_new_win_times; }
      set { _qualifying_new_win_times = value; }
    }
    private uint _skill_reach = default(uint);
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"skill_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_reach
    {
      get { return _skill_reach; }
      set { _skill_reach = value; }
    }
    private uint _qualifying_new_reach = default(uint);
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"qualifying_new_reach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_new_reach
    {
      get { return _qualifying_new_reach; }
      set { _qualifying_new_reach = value; }
    }
    private uint _online_battle_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(61, IsRequired = false, Name=@"online_battle_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint online_battle_win_times
    {
      get { return _online_battle_win_times; }
      set { _online_battle_win_times = value; }
    }
    private uint _qualifying_new_score = default(uint);
    [global::ProtoBuf.ProtoMember(62, IsRequired = false, Name=@"qualifying_new_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_new_score
    {
      get { return _qualifying_new_score; }
      set { _qualifying_new_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskConditionDaily")]
  public partial class TaskConditionDaily : global::ProtoBuf.IExtensible
  {
    public TaskConditionDaily() {}
    
    private uint _buy_gold_times = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"buy_gold_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint buy_gold_times
    {
      get { return _buy_gold_times; }
      set { _buy_gold_times = value; }
    }
    private uint _buy_hp_times = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buy_hp_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint buy_hp_times
    {
      get { return _buy_hp_times; }
      set { _buy_hp_times = value; }
    }
    private uint _regular_race_times = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"regular_race_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regular_race_times
    {
      get { return _regular_race_times; }
      set { _regular_race_times = value; }
    }
    private uint _regular_race_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"regular_race_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regular_race_win_times
    {
      get { return _regular_race_win_times; }
      set { _regular_race_win_times = value; }
    }
    private uint _x_skill_level_up = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"x_skill_level_up", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x_skill_level_up
    {
      get { return _x_skill_level_up; }
      set { _x_skill_level_up = value; }
    }
    private uint _complete_section_times = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"complete_section_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint complete_section_times
    {
      get { return _complete_section_times; }
      set { _complete_section_times = value; }
    }
    private uint _complete_boss_section_times = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"complete_boss_section_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint complete_boss_section_times
    {
      get { return _complete_boss_section_times; }
      set { _complete_boss_section_times = value; }
    }
    private uint _do_training_times = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"do_training_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint do_training_times
    {
      get { return _do_training_times; }
      set { _do_training_times = value; }
    }
    private uint _x_tattoo_level_up = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"x_tattoo_level_up", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x_tattoo_level_up
    {
      get { return _x_tattoo_level_up; }
      set { _x_tattoo_level_up = value; }
    }
    private uint _tour_times = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"tour_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tour_times
    {
      get { return _tour_times; }
      set { _tour_times = value; }
    }
    private uint _qualifying_times = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"qualifying_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_times
    {
      get { return _qualifying_times; }
      set { _qualifying_times = value; }
    }
    private uint _qualifying_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"qualifying_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_win_times
    {
      get { return _qualifying_win_times; }
      set { _qualifying_win_times = value; }
    }
    private uint _new_games_times = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"new_games_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint new_games_times
    {
      get { return _new_games_times; }
      set { _new_games_times = value; }
    }
    private uint _challenge_times = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"challenge_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint challenge_times
    {
      get { return _challenge_times; }
      set { _challenge_times = value; }
    }
    private uint _lottery_times = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"lottery_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lottery_times
    {
      get { return _lottery_times; }
      set { _lottery_times = value; }
    }
    private uint _challenge_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"challenge_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint challenge_win_times
    {
      get { return _challenge_win_times; }
      set { _challenge_win_times = value; }
    }
    private uint _practice_times = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"practice_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint practice_times
    {
      get { return _practice_times; }
      set { _practice_times = value; }
    }
    private uint _bullfight_times = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"bullfight_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bullfight_times
    {
      get { return _bullfight_times; }
      set { _bullfight_times = value; }
    }
    private uint _perday_login = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"perday_login", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint perday_login
    {
      get { return _perday_login; }
      set { _perday_login = value; }
    }
    private uint _online_battle = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"online_battle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint online_battle
    {
      get { return _online_battle; }
      set { _online_battle = value; }
    }
    private uint _qualifying_new_times = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"qualifying_new_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_new_times
    {
      get { return _qualifying_new_times; }
      set { _qualifying_new_times = value; }
    }
    private uint _battle_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"battle_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battle_win_times
    {
      get { return _battle_win_times; }
      set { _battle_win_times = value; }
    }
    private uint _with_friend_ladder = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"with_friend_ladder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint with_friend_ladder
    {
      get { return _with_friend_ladder; }
      set { _with_friend_ladder = value; }
    }
    private uint _ladder_mvp_times = default(uint);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"ladder_mvp_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ladder_mvp_times
    {
      get { return _ladder_mvp_times; }
      set { _ladder_mvp_times = value; }
    }
    private uint _online_battle_get_score = default(uint);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"online_battle_get_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint online_battle_get_score
    {
      get { return _online_battle_get_score; }
      set { _online_battle_get_score = value; }
    }
    private uint _get_money = default(uint);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"get_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_money
    {
      get { return _get_money; }
      set { _get_money = value; }
    }
    private uint _make_badge = default(uint);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"make_badge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint make_badge
    {
      get { return _make_badge; }
      set { _make_badge = value; }
    }
    private uint _qualifying_newer_win_times = default(uint);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"qualifying_newer_win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_newer_win_times
    {
      get { return _qualifying_newer_win_times; }
      set { _qualifying_newer_win_times = value; }
    }
    private uint _qualifying_newer_mvp_times = default(uint);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"qualifying_newer_mvp_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_newer_mvp_times
    {
      get { return _qualifying_newer_mvp_times; }
      set { _qualifying_newer_mvp_times = value; }
    }
    private uint _qualifying_newer_team_times = default(uint);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"qualifying_newer_team_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qualifying_newer_team_times
    {
      get { return _qualifying_newer_team_times; }
      set { _qualifying_newer_team_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignReq")]
  public partial class SignReq : global::ProtoBuf.IExtensible
  {
    public SignReq() {}
    
    private fogs.proto.msg.SignType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SignType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignResp")]
  public partial class SignResp : global::ProtoBuf.IExtensible
  {
    public SignResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.SignType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SignType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetSignAwardReq")]
  public partial class GetSignAwardReq : global::ProtoBuf.IExtensible
  {
    public GetSignAwardReq() {}
    
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private fogs.proto.msg.SignAwardType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SignAwardType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetSignAwardResp")]
  public partial class GetSignAwardResp : global::ProtoBuf.IExtensible
  {
    public GetSignAwardResp() {}
    
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private fogs.proto.msg.SignAwardType _type = fogs.proto.msg.SignAwardType.SAT_DAY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.SignAwardType.SAT_DAY)]
    public fogs.proto.msg.SignAwardType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskInfoReq")]
  public partial class TaskInfoReq : global::ProtoBuf.IExtensible
  {
    public TaskInfoReq() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignInfo")]
  public partial class SignInfo : global::ProtoBuf.IExtensible
  {
    public SignInfo() {}
    
    private uint _signed = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"signed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint signed
    {
      get { return _signed; }
      set { _signed = value; }
    }
    private uint _append_sign_times = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"append_sign_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint append_sign_times
    {
      get { return _append_sign_times; }
      set { _append_sign_times = value; }
    }
    private uint _sign_award = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sign_award", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sign_award
    {
      get { return _sign_award; }
      set { _sign_award = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _sign_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"sign_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> sign_list
    {
      get { return _sign_list; }
    }
  
    private uint _signed_times = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"signed_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint signed_times
    {
      get { return _signed_times; }
      set { _signed_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskInfo")]
  public partial class TaskInfo : global::ProtoBuf.IExtensible
  {
    public TaskInfo() {}
    
    private fogs.proto.msg.SignInfo _sign_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sign_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.SignInfo sign_info
    {
      get { return _sign_info; }
      set { _sign_info = value; }
    }
    private uint _last_daily_time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"last_daily_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_daily_time
    {
      get { return _last_daily_time; }
      set { _last_daily_time = value; }
    }
    private fogs.proto.msg.TaskConditionDaily _daily_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"daily_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.TaskConditionDaily daily_info
    {
      get { return _daily_info; }
      set { _daily_info = value; }
    }
    private fogs.proto.msg.TaskConditionMain _main_info = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"main_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.TaskConditionMain main_info
    {
      get { return _main_info; }
      set { _main_info = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskData> _task_list = new global::System.Collections.Generic.List<fogs.proto.msg.TaskData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"task_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskData> task_list
    {
      get { return _task_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskData")]
  public partial class TaskData : global::ProtoBuf.IExtensible
  {
    public TaskData() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _awarded = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"awarded", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint awarded
    {
      get { return _awarded; }
      set { _awarded = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskData.ConditionInfo> _cond_info = new global::System.Collections.Generic.List<fogs.proto.msg.TaskData.ConditionInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"cond_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskData.ConditionInfo> cond_info
    {
      get { return _cond_info; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConditionInfo")]
  public partial class ConditionInfo : global::ProtoBuf.IExtensible
  {
    public ConditionInfo() {}
    
    private uint _condition_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"condition_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint condition_id
    {
      get { return _condition_id; }
      set { _condition_id = value; }
    }
    private uint _condition_need = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"condition_need", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint condition_need
    {
      get { return _condition_need; }
      set { _condition_need = value; }
    }
    private uint _condition_cur = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"condition_cur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint condition_cur
    {
      get { return _condition_cur; }
      set { _condition_cur = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnclaimedInfo")]
  public partial class UnclaimedInfo : global::ProtoBuf.IExtensible
  {
    public UnclaimedInfo() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskInfoResp")]
  public partial class TaskInfoResp : global::ProtoBuf.IExtensible
  {
    public TaskInfoResp() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskData> _task_main_list = new global::System.Collections.Generic.List<fogs.proto.msg.TaskData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"task_main_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskData> task_main_list
    {
      get { return _task_main_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskData> _task_daily_list = new global::System.Collections.Generic.List<fogs.proto.msg.TaskData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"task_daily_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskData> task_daily_list
    {
      get { return _task_daily_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.UnclaimedInfo> _unclaimed_list = new global::System.Collections.Generic.List<fogs.proto.msg.UnclaimedInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"unclaimed_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.UnclaimedInfo> unclaimed_list
    {
      get { return _unclaimed_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTaskAward")]
  public partial class GetTaskAward : global::ProtoBuf.IExtensible
  {
    public GetTaskAward() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTaskAwardResp")]
  public partial class GetTaskAwardResp : global::ProtoBuf.IExtensible
  {
    public GetTaskAwardResp() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnclaimedTaskNumNotify")]
  public partial class UnclaimedTaskNumNotify : global::ProtoBuf.IExtensible
  {
    public UnclaimedTaskNumNotify() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _task_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> task_id
    {
      get { return _task_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyTaskFinish")]
  public partial class NotifyTaskFinish : global::ProtoBuf.IExtensible
  {
    public NotifyTaskFinish() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private fogs.proto.msg.TaskData _task_info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"task_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fogs.proto.msg.TaskData task_info
    {
      get { return _task_info; }
      set { _task_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TaskType")]
    public enum TaskType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FESTIVAL", Value=1)]
      FESTIVAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIN", Value=2)]
      MAIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY", Value=3)]
      DAILY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SIGN", Value=4)]
      SIGN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL", Value=6)]
      LEVEL = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW_COMER", Value=7)]
      NEW_COMER = 7
    }
  
}