//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Tattoo.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TattooSlotProto")]
  public partial class TattooSlotProto : global::ProtoBuf.IExtensible
  {
    public TattooSlotProto() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _tattoo_uuid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tattoo_uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong tattoo_uuid
    {
      get { return _tattoo_uuid; }
      set { _tattoo_uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TattooOperation")]
  public partial class TattooOperation : global::ProtoBuf.IExtensible
  {
    public TattooOperation() {}
    
    private fogs.proto.msg.TattooOperationType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.TattooOperationType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ulong _uuid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _role_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private uint _slot_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TattooOperationResp")]
  public partial class TattooOperationResp : global::ProtoBuf.IExtensible
  {
    public TattooOperationResp() {}
    
    private fogs.proto.msg.TattooOperationType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.TattooOperationType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _uuid = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _role_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private uint _slot_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoodsConsumData")]
  public partial class GoodsConsumData : global::ProtoBuf.IExtensible
  {
    public GoodsConsumData() {}
    
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TattooUpgrade")]
  public partial class TattooUpgrade : global::ProtoBuf.IExtensible
  {
    public TattooUpgrade() {}
    
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.GoodsConsumData> _consumables = new global::System.Collections.Generic.List<fogs.proto.msg.GoodsConsumData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"consumables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.GoodsConsumData> consumables
    {
      get { return _consumables; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TattooUpgradeResp")]
  public partial class TattooUpgradeResp : global::ProtoBuf.IExtensible
  {
    public TattooUpgradeResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TattooType")]
    public enum TattooType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_NECK", Value=1)]
      TT_NECK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_CHEST", Value=2)]
      TT_CHEST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_ARM", Value=3)]
      TT_ARM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_BACK", Value=4)]
      TT_BACK = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_PIECE", Value=5)]
      TT_PIECE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_ALL", Value=6)]
      TT_ALL = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TattooOperationType")]
    public enum TattooOperationType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOT_EQUIP", Value=2)]
      TOT_EQUIP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOT_UNEQUIP", Value=3)]
      TOT_UNEQUIP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOT_UPGRADE", Value=4)]
      TOT_UPGRADE = 4
    }
  
}