//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Badge.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeSlot")]
  public partial class BadgeSlot : global::ProtoBuf.IExtensible
  {
    public BadgeSlot() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private fogs.proto.msg.BadgeSlotStatus _status = fogs.proto.msg.BadgeSlotStatus.LOCKED;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.BadgeSlotStatus.LOCKED)]
    public fogs.proto.msg.BadgeSlotStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private uint _badge_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"badge_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint badge_id
    {
      get { return _badge_id; }
      set { _badge_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeBook")]
  public partial class BadgeBook : global::ProtoBuf.IExtensible
  {
    public BadgeBook() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _been_used = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"been_used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint been_used
    {
      get { return _been_used; }
      set { _been_used = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.BadgeSlot> _slot_list = new global::System.Collections.Generic.List<fogs.proto.msg.BadgeSlot>();
    [global::ProtoBuf.ProtoMember(4, Name=@"slot_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.BadgeSlot> slot_list
    {
      get { return _slot_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeInfo")]
  public partial class BadgeInfo : global::ProtoBuf.IExtensible
  {
    public BadgeInfo() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.BadgeBook> _badge_book = new global::System.Collections.Generic.List<fogs.proto.msg.BadgeBook>();
    [global::ProtoBuf.ProtoMember(1, Name=@"badge_book", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.BadgeBook> badge_book
    {
      get { return _badge_book; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeUnlockSlotReq")]
  public partial class BadgeUnlockSlotReq : global::ProtoBuf.IExtensible
  {
    public BadgeUnlockSlotReq() {}
    
    private uint _book_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"book_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint book_id
    {
      get { return _book_id; }
      set { _book_id = value; }
    }
    private uint _slot_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeUnlockSlotResp")]
  public partial class BadgeUnlockSlotResp : global::ProtoBuf.IExtensible
  {
    public BadgeUnlockSlotResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeBookChangeNameReq")]
  public partial class BadgeBookChangeNameReq : global::ProtoBuf.IExtensible
  {
    public BadgeBookChangeNameReq() {}
    
    private uint _book_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"book_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint book_id
    {
      get { return _book_id; }
      set { _book_id = value; }
    }
    private string _change_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"change_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string change_name
    {
      get { return _change_name; }
      set { _change_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeBookChangeNameResp")]
  public partial class BadgeBookChangeNameResp : global::ProtoBuf.IExtensible
  {
    public BadgeBookChangeNameResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _book_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"book_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint book_id
    {
      get { return _book_id; }
      set { _book_id = value; }
    }
    private string _change_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"change_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string change_name
    {
      get { return _change_name; }
      set { _change_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeAddBookReq")]
  public partial class BadgeAddBookReq : global::ProtoBuf.IExtensible
  {
    public BadgeAddBookReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeAddBookResp")]
  public partial class BadgeAddBookResp : global::ProtoBuf.IExtensible
  {
    public BadgeAddBookResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.BadgeBook _book = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"book", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.BadgeBook book
    {
      get { return _book; }
      set { _book = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeEquipReq")]
  public partial class BadgeEquipReq : global::ProtoBuf.IExtensible
  {
    public BadgeEquipReq() {}
    
    private uint _badge_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"badge_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint badge_id
    {
      get { return _badge_id; }
      set { _badge_id = value; }
    }
    private uint _book_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"book_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint book_id
    {
      get { return _book_id; }
      set { _book_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeEquipResp")]
  public partial class BadgeEquipResp : global::ProtoBuf.IExtensible
  {
    public BadgeEquipResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeUnequipReq")]
  public partial class BadgeUnequipReq : global::ProtoBuf.IExtensible
  {
    public BadgeUnequipReq() {}
    
    private uint _slot_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private uint _book_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"book_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint book_id
    {
      get { return _book_id; }
      set { _book_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeUnequipResp")]
  public partial class BadgeUnequipResp : global::ProtoBuf.IExtensible
  {
    public BadgeUnequipResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeDecomposeReq")]
  public partial class BadgeDecomposeReq : global::ProtoBuf.IExtensible
  {
    public BadgeDecomposeReq() {}
    
    private uint _badge_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"badge_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint badge_id
    {
      get { return _badge_id; }
      set { _badge_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeDecomposeResp")]
  public partial class BadgeDecomposeResp : global::ProtoBuf.IExtensible
  {
    public BadgeDecomposeResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeComposeReq")]
  public partial class BadgeComposeReq : global::ProtoBuf.IExtensible
  {
    public BadgeComposeReq() {}
    
    private uint _dest_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dest_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dest_id
    {
      get { return _dest_id; }
      set { _dest_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeComposeResp")]
  public partial class BadgeComposeResp : global::ProtoBuf.IExtensible
  {
    public BadgeComposeResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeUpdateData")]
  public partial class BadgeUpdateData : global::ProtoBuf.IExtensible
  {
    public BadgeUpdateData() {}
    
    private uint _book_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"book_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint book_id
    {
      get { return _book_id; }
      set { _book_id = value; }
    }
    private uint _slot_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private fogs.proto.msg.BadgeSlotStatus _slot_status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"slot_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.BadgeSlotStatus slot_status
    {
      get { return _slot_status; }
      set { _slot_status = value; }
    }
    private uint _badge_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"badge_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint badge_id
    {
      get { return _badge_id; }
      set { _badge_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BadgeSlotInfoUpdate")]
  public partial class BadgeSlotInfoUpdate : global::ProtoBuf.IExtensible
  {
    public BadgeSlotInfoUpdate() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.BadgeUpdateData> _datas = new global::System.Collections.Generic.List<fogs.proto.msg.BadgeUpdateData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.BadgeUpdateData> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BadgeCG")]
    public enum BadgeCG
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CG_ALL", Value=0)]
      CG_ALL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CG_RED", Value=1)]
      CG_RED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CG_BLUE", Value=2)]
      CG_BLUE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CG_GREEN", Value=3)]
      CG_GREEN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CG_GLODEN", Value=4)]
      CG_GLODEN = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BadgeSlotStatus")]
    public enum BadgeSlotStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCKED", Value=1)]
      LOCKED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCKED_CANPRE_OPEN", Value=2)]
      LOCKED_CANPRE_OPEN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCKED_WILL_OPEN", Value=3)]
      LOCKED_WILL_OPEN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNLOCK", Value=4)]
      UNLOCK = 4
    }
  
}