//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Login.proto
// Note: requires additional types generated from: Base.proto
// Note: requires additional types generated from: Player.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifySdk")]
  public partial class VerifySdk : global::ProtoBuf.IExtensible
  {
    public VerifySdk() {}
    
    private string _cdkey = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cdkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cdkey
    {
      get { return _cdkey; }
      set { _cdkey = value; }
    }
    private string _token_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"token_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token_id
    {
      get { return _token_id; }
      set { _token_id = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _nick_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifySdkResp")]
  public partial class VerifySdkResp : global::ProtoBuf.IExtensible
  {
    public VerifySdkResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _cdkey = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cdkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cdkey
    {
      get { return _cdkey; }
      set { _cdkey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyCDKey")]
  public partial class VerifyCDKey : global::ProtoBuf.IExtensible
  {
    public VerifyCDKey() {}
    
    private string _authorization_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"authorization_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string authorization_code
    {
      get { return _authorization_code; }
      set { _authorization_code = value; }
    }
    private string _game_ver = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_ver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game_ver
    {
      get { return _game_ver; }
      set { _game_ver = value; }
    }
    private string _res_ver = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"res_ver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string res_ver
    {
      get { return _res_ver; }
      set { _res_ver = value; }
    }
    private string _token_id = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"token_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token_id
    {
      get { return _token_id; }
      set { _token_id = value; }
    }
    private uint _server_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private string _mac_add = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mac_add", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mac_add
    {
      get { return _mac_add; }
      set { _mac_add = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyCDKeyResp")]
  public partial class VerifyCDKeyResp : global::ProtoBuf.IExtensible
  {
    public VerifyCDKeyResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private ulong _session = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong session
    {
      get { return _session; }
      set { _session = value; }
    }
    private uint _login_index = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"login_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint login_index
    {
      get { return _login_index; }
      set { _login_index = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterPlat")]
  public partial class EnterPlat : global::ProtoBuf.IExtensible
  {
    public EnterPlat() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private ulong _session = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong session
    {
      get { return _session; }
      set { _session = value; }
    }
    private uint _login_index = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"login_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint login_index
    {
      get { return _login_index; }
      set { _login_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterPlatResp")]
  public partial class EnterPlatResp : global::ProtoBuf.IExtensible
  {
    public EnterPlatResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _create_step = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"create_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint create_step
    {
      get { return _create_step; }
      set { _create_step = value; }
    }
    private fogs.proto.msg.PlayerInfo _info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PlayerInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private uint _hp_restore_remain = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hp_restore_remain", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp_restore_remain
    {
      get { return _hp_restore_remain; }
      set { _hp_restore_remain = value; }
    }
    private uint _silent_time = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"silent_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint silent_time
    {
      get { return _silent_time; }
      set { _silent_time = value; }
    }
    private uint _silent_start = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"silent_start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint silent_start
    {
      get { return _silent_start; }
      set { _silent_start = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateTeam")]
  public partial class CreateTeam : global::ProtoBuf.IExtensible
  {
    public CreateTeam() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateTeamResp")]
  public partial class CreateTeamResp : global::ProtoBuf.IExtensible
  {
    public CreateTeamResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChooseRole")]
  public partial class ChooseRole : global::ProtoBuf.IExtensible
  {
    public ChooseRole() {}
    
    private uint _role_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChooseRoleResp")]
  public partial class ChooseRoleResp : global::ProtoBuf.IExtensible
  {
    public ChooseRoleResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.PlayerInfo _info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PlayerInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckSession")]
  public partial class CheckSession : global::ProtoBuf.IExtensible
  {
    public CheckSession() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private ulong _session;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong session
    {
      get { return _session; }
      set { _session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckSessionResp")]
  public partial class CheckSessionResp : global::ProtoBuf.IExtensible
  {
    public CheckSessionResp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private string _cdkey = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cdkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cdkey
    {
      get { return _cdkey; }
      set { _cdkey = value; }
    }
    private uint _freshman = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"freshman", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint freshman
    {
      get { return _freshman; }
      set { _freshman = value; }
    }
    private uint _register = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"register", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint register
    {
      get { return _register; }
      set { _register = value; }
    }
    private uint _silent_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"silent_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint silent_time
    {
      get { return _silent_time; }
      set { _silent_time = value; }
    }
    private uint _silent_start = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"silent_start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint silent_start
    {
      get { return _silent_start; }
      set { _silent_start = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateCaptain")]
  public partial class CreateCaptain : global::ProtoBuf.IExtensible
  {
    public CreateCaptain() {}
    
    private fogs.proto.msg.GenderType _gender;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.GenderType gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private fogs.proto.msg.PositionType _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.PositionType position
    {
      get { return _position; }
      set { _position = value; }
    }
    private fogs.proto.msg.CaptainBias _bias;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bias", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.CaptainBias bias
    {
      get { return _bias; }
      set { _bias = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateStepIn")]
  public partial class CreateStepIn : global::ProtoBuf.IExtensible
  {
    public CreateStepIn() {}
    
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _step = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint step
    {
      get { return _step; }
      set { _step = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateStepInResp")]
  public partial class CreateStepInResp : global::ProtoBuf.IExtensible
  {
    public CreateStepInResp() {}
    
    private uint _acc_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _step = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint step
    {
      get { return _step; }
      set { _step = value; }
    }
    private fogs.proto.msg.RoleInfo _role = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.RoleInfo role
    {
      get { return _role; }
      set { _role = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Logout")]
  public partial class Logout : global::ProtoBuf.IExtensible
  {
    public Logout() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutResp")]
  public partial class LogoutResp : global::ProtoBuf.IExtensible
  {
    public LogoutResp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClearUserAcc")]
  public partial class ClearUserAcc : global::ProtoBuf.IExtensible
  {
    public ClearUserAcc() {}
    
    private uint _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint acc_id
    {
      get { return _acc_id; }
      set { _acc_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerListInfo")]
  public partial class ServerListInfo : global::ProtoBuf.IExtensible
  {
    public ServerListInfo() {}
    
    private string _plat_ip = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"plat_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string plat_ip
    {
      get { return _plat_ip; }
      set { _plat_ip = value; }
    }
    private uint _plat_port = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"plat_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint plat_port
    {
      get { return _plat_port; }
      set { _plat_port = value; }
    }
    private string _server_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server_name
    {
      get { return _server_name; }
      set { _server_name = value; }
    }
    private uint _server_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _load = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"load", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint load
    {
      get { return _load; }
      set { _load = value; }
    }
    private uint _sdk_verify = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sdk_verify", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_verify
    {
      get { return _sdk_verify; }
      set { _sdk_verify = value; }
    }
    private uint _default_server = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"default_server", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint default_server
    {
      get { return _default_server; }
      set { _default_server = value; }
    }
    private uint _mac_add_verify = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"mac_add_verify", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mac_add_verify
    {
      get { return _mac_add_verify; }
      set { _mac_add_verify = value; }
    }
    private uint _display_server_id = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"display_server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint display_server_id
    {
      get { return _display_server_id; }
      set { _display_server_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfoReq")]
  public partial class ServerInfoReq : global::ProtoBuf.IExtensible
  {
    public ServerInfoReq() {}
    
    private string _cdkey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cdkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cdkey
    {
      get { return _cdkey; }
      set { _cdkey = value; }
    }
    private string _mac_add;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mac_add", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mac_add
    {
      get { return _mac_add; }
      set { _mac_add = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfoResp")]
  public partial class ServerInfoResp : global::ProtoBuf.IExtensible
  {
    public ServerInfoResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ServerListInfo> _info = new global::System.Collections.Generic.List<fogs.proto.msg.ServerListInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ServerListInfo> info
    {
      get { return _info; }
    }
  
    private uint _last_server_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"last_server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_server_id
    {
      get { return _last_server_id; }
      set { _last_server_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}