//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Message.proto
namespace fogs.proto.msg
{
    [global::ProtoBuf.ProtoContract(Name=@"MsgID")]
    public enum MsgID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HandshakeRequestID", Value=1)]
      HandshakeRequestID = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HandshakeResponseID", Value=2)]
      HandshakeResponseID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheatKickOutID", Value=16)]
      CheatKickOutID = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReportServerLoadID", Value=80)]
      ReportServerLoadID = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeartbeatID", Value=96)]
      HeartbeatID = 96,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReloadLuaFileID", Value=112)]
      ReloadLuaFileID = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnNewDayComeID", Value=113)]
      OnNewDayComeID = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeToClientID", Value=114)]
      NoticeToClientID = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AccountQueryID", Value=256)]
      AccountQueryID = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AccountQueryRespID", Value=257)]
      AccountQueryRespID = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerQueryID", Value=258)]
      PlayerQueryID = 258,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerQueryRespID", Value=259)]
      PlayerQueryRespID = 259,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NameQueryID", Value=260)]
      NameQueryID = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NameQueryRespID", Value=261)]
      NameQueryRespID = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailQueryID", Value=262)]
      MailQueryID = 262,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailQueryRespID", Value=263)]
      MailQueryRespID = 263,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkdPassID", Value=265)]
      SkdPassID = 265,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectServerID", Value=266)]
      SelectServerID = 266,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RechargeOrderQueryID", Value=267)]
      RechargeOrderQueryID = 267,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RechargeOrderQueryRespID", Value=268)]
      RechargeOrderQueryRespID = 268,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerRealTimeSaveID", Value=269)]
      PlayerRealTimeSaveID = 269,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendQueryReqID", Value=270)]
      FriendQueryReqID = 270,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendQueryRespID", Value=271)]
      FriendQueryRespID = 271,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TransferQueryPlayerReqID", Value=272)]
      TransferQueryPlayerReqID = 272,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TransferQueryPlayerRespID", Value=273)]
      TransferQueryPlayerRespID = 273,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginAndlogoutLogID", Value=336)]
      LoginAndlogoutLogID = 336,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnlineUserCountLogID", Value=337)]
      OnlineUserCountLogID = 337,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateCharacterLogID", Value=338)]
      CreateCharacterLogID = 338,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GoodsProduceAndConsumeLogID", Value=339)]
      GoodsProduceAndConsumeLogID = 339,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinGameLogID", Value=340)]
      JoinGameLogID = 340,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RechargeAndExpenseLogID", Value=341)]
      RechargeAndExpenseLogID = 341,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchRecordLogID", Value=342)]
      MatchRecordLogID = 342,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CareerPassOnlineTimeID", Value=343)]
      CareerPassOnlineTimeID = 343,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RechargeLogID", Value=344)]
      RechargeLogID = 344,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeLogID", Value=345)]
      NoticeLogID = 345,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatLogID", Value=346)]
      ChatLogID = 346,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchingLogID", Value=347)]
      MatchingLogID = 347,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchingTimeLogID", Value=348)]
      MatchingTimeLogID = 348,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameDataLogID", Value=349)]
      GameDataLogID = 349,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FirstFightGuideModuleLogID", Value=350)]
      FirstFightGuideModuleLogID = 350,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RankLogID", Value=351)]
      RankLogID = 351,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SocialContactLogID", Value=352)]
      SocialContactLogID = 352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinActivityLogID", Value=353)]
      JoinActivityLogID = 353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TaskLogID", Value=354)]
      TaskLogID = 354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LivenessLogID", Value=355)]
      LivenessLogID = 355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSkillLogID", Value=356)]
      EquipSkillLogID = 356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FirstLotteryLogID", Value=357)]
      FirstLotteryLogID = 357,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VerifyVersionID", Value=512)]
      VerifyVersionID = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VerifyVersionRespID", Value=513)]
      VerifyVersionRespID = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VerifyCDKeyID", Value=514)]
      VerifyCDKeyID = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VerifyCDKeyRespID", Value=515)]
      VerifyCDKeyRespID = 515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerInfoReqID", Value=517)]
      ServerInfoReqID = 517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerInfoRespID", Value=518)]
      ServerInfoRespID = 518,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VerifySdkID", Value=519)]
      VerifySdkID = 519,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VerifySdkRespID", Value=520)]
      VerifySdkRespID = 520,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterPlatID", Value=528)]
      EnterPlatID = 528,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterPlatRespID", Value=529)]
      EnterPlatRespID = 529,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheckSessionID", Value=530)]
      CheckSessionID = 530,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheckSessionRespID", Value=531)]
      CheckSessionRespID = 531,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateTeamID", Value=532)]
      CreateTeamID = 532,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateTeamRespID", Value=533)]
      CreateTeamRespID = 533,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChooseRoleID", Value=534)]
      ChooseRoleID = 534,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChooseRoleRespID", Value=535)]
      ChooseRoleRespID = 535,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateCaptainID", Value=536)]
      CreateCaptainID = 536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyCaptainID", Value=537)]
      BuyCaptainID = 537,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyCaptainRespID", Value=538)]
      BuyCaptainRespID = 538,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SwitchCaptainID", Value=539)]
      SwitchCaptainID = 539,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SwitchCaptainRespID", Value=540)]
      SwitchCaptainRespID = 540,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartTrainingID", Value=541)]
      StartTrainingID = 541,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartTrainingRespID", Value=542)]
      StartTrainingRespID = 542,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyTrainingInfoID", Value=543)]
      NotifyTrainingInfoID = 543,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TrainingUpConfirmID", Value=544)]
      TrainingUpConfirmID = 544,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TrainingUpConfirmRespID", Value=545)]
      TrainingUpConfirmRespID = 545,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OpenTrainingID", Value=546)]
      OpenTrainingID = 546,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OpenTrainingRespID", Value=547)]
      OpenTrainingRespID = 547,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateStepInID", Value=560)]
      CreateStepInID = 560,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateStepInRespID", Value=561)]
      CreateStepInRespID = 561,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogoutID", Value=768)]
      LogoutID = 768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogoutRespID", Value=769)]
      LogoutRespID = 769,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetPlayerDataID", Value=1024)]
      SetPlayerDataID = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangePlayerDataID", Value=1025)]
      ChangePlayerDataID = 1025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePlayerDataID", Value=1026)]
      UpdatePlayerDataID = 1026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateGoodsID", Value=1027)]
      UpdateGoodsID = 1027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetFreeHpReqID", Value=1040)]
      GetFreeHpReqID = 1040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetFreeHpRespID", Value=1041)]
      GetFreeHpRespID = 1041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyLotteryReqID", Value=1088)]
      BuyLotteryReqID = 1088,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyLotteryRespID", Value=1089)]
      BuyLotteryRespID = 1089,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerVipOperationID", Value=1104)]
      PlayerVipOperationID = 1104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerVipOperationRespID", Value=1105)]
      PlayerVipOperationRespID = 1105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateVipInfoID", Value=1107)]
      UpdateVipInfoID = 1107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SellGoodsID", Value=1120)]
      SellGoodsID = 1120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SellGoodsRespID", Value=1121)]
      SellGoodsRespID = 1121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UseGoodsID", Value=1122)]
      UseGoodsID = 1122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UseGoodsRespID", Value=1123)]
      UseGoodsRespID = 1123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompositeGoodsID", Value=1124)]
      CompositeGoodsID = 1124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompositeGoodsRespID", Value=1125)]
      CompositeGoodsRespID = 1125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DecomposeGoodsID", Value=1126)]
      DecomposeGoodsID = 1126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DecomposeGoodsRespID", Value=1127)]
      DecomposeGoodsRespID = 1127,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillOperationID", Value=1136)]
      SkillOperationID = 1136,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillOperationRespID", Value=1137)]
      SkillOperationRespID = 1137,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TattooOperationID", Value=1152)]
      TattooOperationID = 1152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TattooOperationRespID", Value=1153)]
      TattooOperationRespID = 1153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TattooUpgradeID", Value=1154)]
      TattooUpgradeID = 1154,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TattooUpgradeRespID", Value=1155)]
      TattooUpgradeRespID = 1155,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FashionOperationID", Value=1168)]
      FashionOperationID = 1168,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FashionOperationRespID", Value=1169)]
      FashionOperationRespID = 1169,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FashionResetAttrReqID", Value=1170)]
      FashionResetAttrReqID = 1170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FashionResetAttrRespID", Value=1171)]
      FashionResetAttrRespID = 1171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipOperationID", Value=1173)]
      EquipOperationID = 1173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipOperationRespID", Value=1174)]
      EquipOperationRespID = 1174,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartSectionMatchID", Value=1280)]
      StartSectionMatchID = 1280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartSectionMatchRespID", Value=1281)]
      StartSectionMatchRespID = 1281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndSectionMatchID", Value=1282)]
      EndSectionMatchID = 1282,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndSectionMatchRespID", Value=1283)]
      EndSectionMatchRespID = 1283,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SweepSectionID", Value=1284)]
      SweepSectionID = 1284,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SweepSectionRespID", Value=1285)]
      SweepSectionRespID = 1285,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetChapterStarAwardID", Value=1286)]
      GetChapterStarAwardID = 1286,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetChapterStarAwardRespID", Value=1287)]
      GetChapterStarAwardRespID = 1287,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetSectionChallengeTimesID", Value=1288)]
      ResetSectionChallengeTimesID = 1288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetSectionChallengeTimesRespID", Value=1289)]
      ResetSectionChallengeTimesRespID = 1289,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddNewChapterID", Value=1290)]
      AddNewChapterID = 1290,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ImproveQualityReqID", Value=1536)]
      ImproveQualityReqID = 1536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ImproveQualityRespID", Value=1537)]
      ImproveQualityRespID = 1537,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InviteRoleReqID", Value=1538)]
      InviteRoleReqID = 1538,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InviteRoleRespID", Value=1539)]
      InviteRoleRespID = 1539,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddRolePiecesID", Value=1540)]
      AddRolePiecesID = 1540,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddRolePiecesRespID", Value=1541)]
      AddRolePiecesRespID = 1541,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnhanceLevelReqID", Value=1542)]
      EnhanceLevelReqID = 1542,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnhanceLevelRespID", Value=1543)]
      EnhanceLevelRespID = 1543,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnhanceExerciseReqID", Value=1544)]
      EnhanceExerciseReqID = 1544,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnhanceExerciseRespID", Value=1545)]
      EnhanceExerciseRespID = 1545,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetRoleReqID", Value=1552)]
      ResetRoleReqID = 1552,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetRoleRespID", Value=1553)]
      ResetRoleRespID = 1553,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OpenStoreID", Value=1792)]
      OpenStoreID = 1792,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OpenStoreRespID", Value=1793)]
      OpenStoreRespID = 1793,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshStoreGoodsID", Value=1794)]
      RefreshStoreGoodsID = 1794,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshStoreGoodsRespID", Value=1795)]
      RefreshStoreGoodsRespID = 1795,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyStoreGoodsID", Value=1796)]
      BuyStoreGoodsID = 1796,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyStoreGoodsRespID", Value=1797)]
      BuyStoreGoodsRespID = 1797,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeFightRoleID", Value=2048)]
      ChangeFightRoleID = 2048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeFightRoleRespID", Value=2049)]
      ChangeFightRoleRespID = 2049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateFightRoleID", Value=2050)]
      UpdateFightRoleID = 2050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewComerSignReqID", Value=2064)]
      NewComerSignReqID = 2064,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewComerSignRespID", Value=2065)]
      NewComerSignRespID = 2065,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewDayComeID", Value=2066)]
      NewDayComeID = 2066,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatReqID", Value=2067)]
      ChatReqID = 2067,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatBroadcastID", Value=2068)]
      ChatBroadcastID = 2068,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRespID", Value=2069)]
      ChatRespID = 2069,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueryPlayerInfoReqID", Value=2070)]
      QueryPlayerInfoReqID = 2070,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueryPlayerInfoRespID", Value=2071)]
      QueryPlayerInfoRespID = 2071,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatLatestInfoReqID", Value=2072)]
      ChatLatestInfoReqID = 2072,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatLatestInfoRespID", Value=2073)]
      ChatLatestInfoRespID = 2073,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateRoleMapAddAttrID", Value=2080)]
      UpdateRoleMapAddAttrID = 2080,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewComerTrialNotifyID", Value=2096)]
      NewComerTrialNotifyID = 2096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetNewComerTrialAwardsReqID", Value=2097)]
      GetNewComerTrialAwardsReqID = 2097,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetNewComerTrialAwardsRespID", Value=2098)]
      GetNewComerTrialAwardsRespID = 2098,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendOperationReqID", Value=2112)]
      FriendOperationReqID = 2112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendOperationRespID", Value=2113)]
      FriendOperationRespID = 2113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueryFriendInfoReqID", Value=2114)]
      QueryFriendInfoReqID = 2114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueryFriendInfoRespID", Value=2115)]
      QueryFriendInfoRespID = 2115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyFriendInfoID", Value=2116)]
      NotifyFriendInfoID = 2116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePlayerInfoID", Value=2117)]
      UpdatePlayerInfoID = 2117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyOffLineInfoToPlayerID", Value=2118)]
      NotifyOffLineInfoToPlayerID = 2118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SearchFriendID", Value=2119)]
      SearchFriendID = 2119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SearchFriendRespID", Value=2120)]
      SearchFriendRespID = 2120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterRaceReqID", Value=2304)]
      EnterRaceReqID = 2304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterRaceRespID", Value=2305)]
      EnterRaceRespID = 2305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndRaceReqID", Value=2306)]
      EndRaceReqID = 2306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndRaceRespID", Value=2307)]
      EndRaceRespID = 2307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitRaceReqID", Value=2308)]
      ExitRaceReqID = 2308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitRaceRespID", Value=2309)]
      ExitRaceRespID = 2309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyRaceTimesReqID", Value=2310)]
      BuyRaceTimesReqID = 2310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyRaceTimesRespID", Value=2311)]
      BuyRaceTimesRespID = 2311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AsynEnterRoomReqID", Value=2312)]
      AsynEnterRoomReqID = 2312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AsynEnterRoomRespID", Value=2313)]
      AsynEnterRoomRespID = 2313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AsynExitRoomReqID", Value=2314)]
      AsynExitRoomReqID = 2314,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AsynExitRoomRespID", Value=2315)]
      AsynExitRoomRespID = 2315,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RankListReqID", Value=2320)]
      RankListReqID = 2320,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RankListRespID", Value=2321)]
      RankListRespID = 2321,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FetchRankListReqID", Value=2336)]
      FetchRankListReqID = 2336,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FetchRankListRespID", Value=2337)]
      FetchRankListRespID = 2337,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateRankListReqID", Value=2338)]
      UpdateRankListReqID = 2338,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateRankListRespID", Value=2339)]
      UpdateRankListRespID = 2339,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateRankListID", Value=2340)]
      UpdateRankListID = 2340,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourResetReqID", Value=2352)]
      TourResetReqID = 2352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourResetRespID", Value=2353)]
      TourResetRespID = 2353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourStartReqID", Value=2354)]
      TourStartReqID = 2354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourStartRespID", Value=2355)]
      TourStartRespID = 2355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourCompleteReqID", Value=2356)]
      TourCompleteReqID = 2356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourCompleteRespID", Value=2357)]
      TourCompleteRespID = 2357,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourExitReqID", Value=2358)]
      TourExitReqID = 2358,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourExitRespID", Value=2359)]
      TourExitRespID = 2359,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetTourNpcID", Value=2360)]
      ResetTourNpcID = 2360,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateTourInfoReqID", Value=2361)]
      UpdateTourInfoReqID = 2361,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateTourInfoRespID", Value=2362)]
      UpdateTourInfoRespID = 2362,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourBuyChallengeTimesReqID", Value=2363)]
      TourBuyChallengeTimesReqID = 2363,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TourBuyChallengeTimesRespID", Value=2364)]
      TourBuyChallengeTimesRespID = 2364,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyPlayerDataID", Value=2368)]
      NotifyPlayerDataID = 2368,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FlushRivalReqID", Value=2384)]
      FlushRivalReqID = 2384,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FlushRivalRespID", Value=2385)]
      FlushRivalRespID = 2385,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetDefendReqID", Value=2386)]
      SetDefendReqID = 2386,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetDefendRespID", Value=2387)]
      SetDefendRespID = 2387,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetBattleCDReqID", Value=2388)]
      ResetBattleCDReqID = 2388,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetBattleCDRespID", Value=2389)]
      ResetBattleCDRespID = 2389,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetBattleNewsID", Value=2390)]
      GetBattleNewsID = 2390,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetBattleNewsRespID", Value=2391)]
      GetBattleNewsRespID = 2391,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QualifyingBuyTimesReqID", Value=2392)]
      QualifyingBuyTimesReqID = 2392,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QualifyingBuyTimesRespID", Value=2393)]
      QualifyingBuyTimesRespID = 2393,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QualifyingRankingNotifyID", Value=2394)]
      QualifyingRankingNotifyID = 2394,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FightPowerChangeID", Value=2395)]
      FightPowerChangeID = 2395,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshQualifyingNewInfoID", Value=2396)]
      RefreshQualifyingNewInfoID = 2396,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshLadderInfoID", Value=2400)]
      RefreshLadderInfoID = 2400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyLadderLeagueResetID", Value=2401)]
      NotifyLadderLeagueResetID = 2401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetLadderLeagueAwardsReqID", Value=2402)]
      GetLadderLeagueAwardsReqID = 2402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetLadderLeagueAwardsRespID", Value=2403)]
      GetLadderLeagueAwardsRespID = 2403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshQualifyingNewerInfoID", Value=2416)]
      RefreshQualifyingNewerInfoID = 2416,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyQualifyingNewerLeagueResetID", Value=2417)]
      NotifyQualifyingNewerLeagueResetID = 2417,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetQualifyingNewerGradesAwardsReqID", Value=2418)]
      GetQualifyingNewerGradesAwardsReqID = 2418,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetQualifyingNewerGradesAwardsRespID", Value=2419)]
      GetQualifyingNewerGradesAwardsRespID = 2419,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetQualifyingNewerLeagueAwardsReqID", Value=2420)]
      GetQualifyingNewerLeagueAwardsReqID = 2420,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetQualifyingNewerLeagueAwardsRespID", Value=2421)]
      GetQualifyingNewerLeagueAwardsRespID = 2421,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetTourNewGradesAwardsReqID", Value=2432)]
      GetTourNewGradesAwardsReqID = 2432,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetTourNewGradesAwardsRespID", Value=2433)]
      GetTourNewGradesAwardsRespID = 2433,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TaskInfoReqID", Value=4096)]
      TaskInfoReqID = 4096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TaskInfoRespID", Value=4097)]
      TaskInfoRespID = 4097,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetTaskAwardReqID", Value=4098)]
      GetTaskAwardReqID = 4098,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetTaskAwardRespID", Value=4099)]
      GetTaskAwardRespID = 4099,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnclaimedTaskNumNotifyID", Value=4100)]
      UnclaimedTaskNumNotifyID = 4100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SignReqID", Value=4101)]
      SignReqID = 4101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SignRespID", Value=4102)]
      SignRespID = 4102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetSignAwardReqID", Value=4103)]
      GetSignAwardReqID = 4103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetSignAwardRespID", Value=4104)]
      GetSignAwardRespID = 4104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyTaskFinishID", Value=4105)]
      NotifyTaskFinishID = 4105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BeginPracticeID", Value=4432)]
      BeginPracticeID = 4432,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BeginPracticeRespID", Value=4433)]
      BeginPracticeRespID = 4433,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndPracticeID", Value=4434)]
      EndPracticeID = 4434,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndPracticeRespID", Value=4435)]
      EndPracticeRespID = 4435,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitPracticeID", Value=4436)]
      ExitPracticeID = 4436,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitPracticeRespID", Value=4437)]
      ExitPracticeRespID = 4437,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OpenMailSysID", Value=4608)]
      OpenMailSysID = 4608,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailInfoNotifyID", Value=4609)]
      MailInfoNotifyID = 4609,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewMailNotifyID", Value=4610)]
      NewMailNotifyID = 4610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReadMailID", Value=4611)]
      ReadMailID = 4611,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReadMailRespID", Value=4612)]
      ReadMailRespID = 4612,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetAttachmentID", Value=4613)]
      GetAttachmentID = 4613,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetAttachmentRespID", Value=4614)]
      GetAttachmentRespID = 4614,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetBullFightNpcReqID", Value=4624)]
      GetBullFightNpcReqID = 4624,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetBullFightNpcRespID", Value=4625)]
      GetBullFightNpcRespID = 4625,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyBullFightTimesReqID", Value=4626)]
      BuyBullFightTimesReqID = 4626,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyBullFightTimesRespID", Value=4627)]
      BuyBullFightTimesRespID = 4627,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShootOpenReqID", Value=4640)]
      ShootOpenReqID = 4640,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShootOpenRespID", Value=4641)]
      ShootOpenRespID = 4641,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShootBuyTimesReqID", Value=4642)]
      ShootBuyTimesReqID = 4642,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShootBuyTimesRespID", Value=4643)]
      ShootBuyTimesRespID = 4643,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShootOpenCardReqID", Value=4644)]
      ShootOpenCardReqID = 4644,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShootOpendCardRespID", Value=4645)]
      ShootOpendCardRespID = 4645,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BeginGuideReqID", Value=4864)]
      BeginGuideReqID = 4864,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BeginGuideRespID", Value=4865)]
      BeginGuideRespID = 4865,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndGuideReqID", Value=4866)]
      EndGuideReqID = 4866,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndGuideRespID", Value=4867)]
      EndGuideRespID = 4867,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FirstFightGuideModuleReqID", Value=4868)]
      FirstFightGuideModuleReqID = 4868,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetActivityAwardsReqID", Value=4880)]
      GetActivityAwardsReqID = 4880,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetActivityAwardsRespID", Value=4881)]
      GetActivityAwardsRespID = 4881,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateActivityInfoID", Value=4882)]
      UpdateActivityInfoID = 4882,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeUnlockSlotReqID", Value=4944)]
      BadgeUnlockSlotReqID = 4944,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeUnlockSlotRespID", Value=4945)]
      BadgeUnlockSlotRespID = 4945,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeBookChangeNameReqID", Value=4946)]
      BadgeBookChangeNameReqID = 4946,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeBookChangeNameRespID", Value=4947)]
      BadgeBookChangeNameRespID = 4947,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeAddBookReqID", Value=4948)]
      BadgeAddBookReqID = 4948,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeAddBookRespID", Value=4949)]
      BadgeAddBookRespID = 4949,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeEquipReqID", Value=4950)]
      BadgeEquipReqID = 4950,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeEquipRespID", Value=4951)]
      BadgeEquipRespID = 4951,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeUnequipReqID", Value=4952)]
      BadgeUnequipReqID = 4952,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeUnequipRespID", Value=4953)]
      BadgeUnequipRespID = 4953,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeDecomposeReqID", Value=4954)]
      BadgeDecomposeReqID = 4954,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeDecomposeRespID", Value=4955)]
      BadgeDecomposeRespID = 4955,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeComposeReqID", Value=4956)]
      BadgeComposeReqID = 4956,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeComposeRespID", Value=4957)]
      BadgeComposeRespID = 4957,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeSlotInfoUpdateID", Value=4958)]
      BadgeSlotInfoUpdateID = 4958,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeBookUseReqID", Value=4959)]
      BadgeBookUseReqID = 4959,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeDecomposeByGroupReqID", Value=4960)]
      BadgeDecomposeByGroupReqID = 4960,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeDecomposeByGroupRespID", Value=4961)]
      BadgeDecomposeByGroupRespID = 4961,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeChangeReqID", Value=4962)]
      BadgeChangeReqID = 4962,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BadgeChangeRespID", Value=4963)]
      BadgeChangeRespID = 4963,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterRoomReqID", Value=8960)]
      EnterRoomReqID = 8960,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterRoomRespID", Value=8961)]
      EnterRoomRespID = 8961,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinRoomReqID", Value=8962)]
      JoinRoomReqID = 8962,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinRoomRespID", Value=8963)]
      JoinRoomRespID = 8963,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitRoomReqID", Value=8966)]
      ExitRoomReqID = 8966,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitRoomRespID", Value=8967)]
      ExitRoomRespID = 8967,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomActionReqID", Value=8968)]
      RoomActionReqID = 8968,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomActionRespID", Value=8969)]
      RoomActionRespID = 8969,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyRoomUserID", Value=8970)]
      NotifyRoomUserID = 8970,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyRoomUserExitID", Value=8971)]
      NotifyRoomUserExitID = 8971,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVPReadyReqID", Value=8972)]
      PVPReadyReqID = 8972,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVPReadyRespID", Value=8973)]
      PVPReadyRespID = 8973,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRoomReqID", Value=8974)]
      CreateRoomReqID = 8974,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRoomRespID", Value=8975)]
      CreateRoomRespID = 8975,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartMatchReqID", Value=8976)]
      StartMatchReqID = 8976,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartMatchRespID", Value=8977)]
      StartMatchRespID = 8977,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CancelMatchReqID", Value=8978)]
      CancelMatchReqID = 8978,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CancelMatchRespID", Value=8979)]
      CancelMatchRespID = 8979,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateGameReqID", Value=8980)]
      CreateGameReqID = 8980,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateGameRespID", Value=8981)]
      CreateGameRespID = 8981,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartGameReqID", Value=8982)]
      StartGameReqID = 8982,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartGameRespID", Value=8983)]
      StartGameRespID = 8983,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterGameReqID", Value=8984)]
      EnterGameReqID = 8984,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterGameRespID", Value=8985)]
      EnterGameRespID = 8985,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitGameReqID", Value=8986)]
      ExitGameReqID = 8986,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitGameRespID", Value=8987)]
      ExitGameRespID = 8987,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequirePlayerDataID", Value=8988)]
      RequirePlayerDataID = 8988,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequirePlayerDataRespID", Value=8989)]
      RequirePlayerDataRespID = 8989,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyGameStartID", Value=8990)]
      NotifyGameStartID = 8990,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyGameStartRespID", Value=8991)]
      NotifyGameStartRespID = 8991,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyMatchInfoID", Value=8992)]
      NotifyMatchInfoID = 8992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectFightRoleID", Value=8993)]
      SelectFightRoleID = 8993,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifySelectFightRoleID", Value=8994)]
      NotifySelectFightRoleID = 8994,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchOverID", Value=8995)]
      MatchOverID = 8995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitSelectRoleUIID", Value=8996)]
      ExitSelectRoleUIID = 8996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomInfoReqID", Value=9008)]
      RoomInfoReqID = 9008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyUserReturnID", Value=9009)]
      NotifyUserReturnID = 9009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterGameSrvID", Value=9216)]
      EnterGameSrvID = 9216,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterGameSrvRespID", Value=9217)]
      EnterGameSrvRespID = 9217,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FirstWinInfoID", Value=9248)]
      FirstWinInfoID = 9248,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StandID", Value=9472)]
      StandID = 9472,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveID", Value=9473)]
      MoveID = 9473,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameMsgID", Value=9474)]
      GameMsgID = 9474,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InputID", Value=9475)]
      InputID = 9475,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DisturbID", Value=9476)]
      DisturbID = 9476,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillID", Value=9477)]
      SkillID = 9477,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HoldID", Value=9478)]
      HoldID = 9478,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequireBallID", Value=9479)]
      RequireBallID = 9479,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CatchBallID", Value=9480)]
      CatchBallID = 9480,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PassBallID", Value=9481)]
      PassBallID = 9481,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickBallID", Value=9482)]
      PickBallID = 9482,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CrossedID", Value=9483)]
      CrossedID = 9483,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CutInID", Value=9484)]
      CutInID = 9484,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickAndRoleID", Value=9485)]
      PickAndRoleID = 9485,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BePickAndRoleID", Value=9486)]
      BePickAndRoleID = 9486,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AttackID", Value=9487)]
      AttackID = 9487,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PrepareToShootID", Value=9488)]
      PrepareToShootID = 9488,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DefenseCrossID", Value=9489)]
      DefenseCrossID = 9489,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DownID", Value=9490)]
      DownID = 9490,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FallDownID", Value=9491)]
      FallDownID = 9491,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockID", Value=9492)]
      BlockID = 9492,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StealID", Value=9493)]
      StealID = 9493,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StolenID", Value=9494)]
      StolenID = 9494,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CrossOverID", Value=9495)]
      CrossOverID = 9495,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReboundID", Value=9496)]
      ReboundID = 9496,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BodyThrowCatchID", Value=9497)]
      BodyThrowCatchID = 9497,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameBeginReqID", Value=9498)]
      GameBeginReqID = 9498,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameBeginRespID", Value=9499)]
      GameBeginRespID = 9499,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameGoalID", Value=9500)]
      GameGoalID = 9500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameFaulID", Value=9501)]
      GameFaulID = 9501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOverID", Value=9502)]
      GameOverID = 9502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVPLoadCompleteID", Value=9503)]
      PVPLoadCompleteID = 9503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVPLoadCompleteRespID", Value=9504)]
      PVPLoadCompleteRespID = 9504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchBeginID", Value=9505)]
      MatchBeginID = 9505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InterceptionID", Value=9506)]
      InterceptionID = 9506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BeginTipOffReqID", Value=9507)]
      BeginTipOffReqID = 9507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BeginTipOffRespID", Value=9508)]
      BeginTipOffRespID = 9508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LayupFailedID", Value=9509)]
      LayupFailedID = 9509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockSuccessID", Value=9510)]
      BlockSuccessID = 9510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BackToBackID", Value=9511)]
      BackToBackID = 9511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BackCompeteID", Value=9512)]
      BackCompeteID = 9512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BackBlockID", Value=9513)]
      BackBlockID = 9513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BackToStandID", Value=9514)]
      BackToStandID = 9514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BackTurnRunID", Value=9515)]
      BackTurnRunID = 9515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BackToBackForwardID", Value=9516)]
      BackToBackForwardID = 9516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamMateStateChangeID", Value=9552)]
      TeamMateStateChangeID = 9552,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InstructionReqID", Value=9568)]
      InstructionReqID = 9568,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InstructionBroadcastID", Value=9569)]
      InstructionBroadcastID = 9569,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientInputID", Value=9584)]
      ClientInputID = 9584,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FrameInfoID", Value=9585)]
      FrameInfoID = 9585,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheckFrameID", Value=9586)]
      CheckFrameID = 9586,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyUnsyncID", Value=9587)]
      NotifyUnsyncID = 9587,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMCommondExcuID", Value=12288)]
      GMCommondExcuID = 12288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PHPReqID", Value=12304)]
      PHPReqID = 12304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerDiscontinueInfoID", Value=32768)]
      ServerDiscontinueInfoID = 32768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RpcID", Value=36864)]
      RpcID = 36864,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RpcAckID", Value=36865)]
      RpcAckID = 36865,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TimeTracerID", Value=36866)]
      TimeTracerID = 36866,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncTimeID", Value=36867)]
      SyncTimeID = 36867,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomCreateReqID", Value=36868)]
      ChatRoomCreateReqID = 36868,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomCreateRespID", Value=36869)]
      ChatRoomCreateRespID = 36869,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomDestroyReqID", Value=36870)]
      ChatRoomDestroyReqID = 36870,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomDestroyRespID", Value=36871)]
      ChatRoomDestroyRespID = 36871,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomDestroyBroadcastID", Value=36872)]
      ChatRoomDestroyBroadcastID = 36872,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomJoinReqID", Value=36873)]
      ChatRoomJoinReqID = 36873,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomJoinRespID", Value=36880)]
      ChatRoomJoinRespID = 36880,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomJoinBroadcastID", Value=36881)]
      ChatRoomJoinBroadcastID = 36881,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomLeaveReqID", Value=36882)]
      ChatRoomLeaveReqID = 36882,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomLeaveRespID", Value=36883)]
      ChatRoomLeaveRespID = 36883,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomLeaveBroadcastID", Value=36884)]
      ChatRoomLeaveBroadcastID = 36884,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomQueryReqID", Value=36885)]
      ChatRoomQueryReqID = 36885,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomQueryRespID", Value=36886)]
      ChatRoomQueryRespID = 36886,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomQueryLatestReqID", Value=36887)]
      ChatRoomQueryLatestReqID = 36887,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomQueryLatestRespID", Value=36888)]
      ChatRoomQueryLatestRespID = 36888,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomDeliverID", Value=36889)]
      ChatRoomDeliverID = 36889,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomBroadcastID", Value=36896)]
      ChatRoomBroadcastID = 36896,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyMatchChatRoomID", Value=36897)]
      NotifyMatchChatRoomID = 36897,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomDeliverRespID", Value=36898)]
      ChatRoomDeliverRespID = 36898,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchChatRoomCreateReqID", Value=36899)]
      MatchChatRoomCreateReqID = 36899,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchChatRoomCreateRespID", Value=36900)]
      MatchChatRoomCreateRespID = 36900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRoomCreateBroadcastID", Value=36901)]
      ChatRoomCreateBroadcastID = 36901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchChatRoomDestroyReqID", Value=36902)]
      MatchChatRoomDestroyReqID = 36902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchChatRoomDestroyRespID", Value=36903)]
      MatchChatRoomDestroyRespID = 36903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVPLoadProgressID", Value=36904)]
      PVPLoadProgressID = 36904,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVPLoadProgressBroadcastID", Value=36905)]
      PVPLoadProgressBroadcastID = 36905,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetLevelAwardReqID", Value=36912)]
      GetLevelAwardReqID = 36912,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetLevelAwardRespID", Value=36913)]
      GetLevelAwardRespID = 36913,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LevelAwardStateReqID", Value=36914)]
      LevelAwardStateReqID = 36914,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LevelAwardStateRespID", Value=36915)]
      LevelAwardStateRespID = 36915
    }
  
}