protogen -i:Base.proto -o:Base.cs
protogen -i:Captain.proto -o:Captain.cs
protogen -i:Career.proto -o:Career.cs
protogen -i:Exercise.proto -o:Exercise.cs
protogen -i:ErrorCode.proto -o:ErrorCode.cs
protogen -i:Fashion.proto -o:Fashion.cs
protogen -i:Game.proto -o:Game.cs
protogen -i:GMCommond.proto -o:GMCommond.cs
protogen -i:Goods.proto -o:Goods.cs
protogen -i:Guide.proto -o:Guide.cs
protogen -i:Login.proto -o:Login.cs
protogen -i:Lottery.proto -o:Lottery.cs
protogen -i:Mail.proto -o:Mail.cs
protogen -i:Match.proto -o:Match.cs
protogen -i:Message.proto -o:Message.cs
protogen -i:Player.proto -o:Player.cs
protogen -i:Practice.proto -o:Practice.cs
protogen -i:Rank.proto -o:Rank.cs
protogen -i:Role.proto -o:Role.cs
protogen -i:Room.proto -o:Room.cs
protogen -i:Scene.proto -o:Scene.cs
protogen -i:Server.proto -o:Server.cs
protogen -i:Skill.proto -o:Skill.cs
protogen -i:Store.proto -o:Store.cs
protogen -i:Task.proto -o:Task.cs
protogen -i:Tattoo.proto -o:Tattoo.cs
protogen -i:Tour.proto -o:Tour.cs
protogen -i:Training.proto -o:Training.cs
protogen -i:Qualifying.proto -o:Qualifying.cs
protogen -i:Rank.proto -o:Rank.cs
protogen -i:XmlConfig.proto -o:XmlConfig.cs
protogen -i:Exercise.proto -o:Exercise.cs
protogen -i:BullFight.proto -o:BullFight.cs
protogen -i:Shoot.proto -o:Shoot.cs
protogen -i:Equipment.proto -o:Equipment.cs
protogen -i:NewComer.proto -o:NewComer.cs
protogen -i:Chat.proto -o:Chat.cs
protogen -i:Activity.proto -o:Activity.cs
protogen -i:Friend.proto -o:Friend.cs
protogen -i:QualifyingNewer.proto -o:QualifyingNewer.cs
pause
