//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Regular.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegularMatchResp")]
  public partial class RegularMatchResp : global::ProtoBuf.IExtensible
  {
    public RegularMatchResp() {}
    
    private ulong _session_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}