//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Store.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StoreGoodsInfo")]
  public partial class StoreGoodsInfo : global::ProtoBuf.IExtensible
  {
    public StoreGoodsInfo() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _price = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint price
    {
      get { return _price; }
      set { _price = value; }
    }
    private uint _consume_type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"consume_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint consume_type
    {
      get { return _consume_type; }
      set { _consume_type = value; }
    }
    private uint _sell_out = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sell_out", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sell_out
    {
      get { return _sell_out; }
      set { _sell_out = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StoreInfo")]
  public partial class StoreInfo : global::ProtoBuf.IExtensible
  {
    public StoreInfo() {}
    
    private uint _refresh_time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"refresh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_time
    {
      get { return _refresh_time; }
      set { _refresh_time = value; }
    }
    private uint _refresh_request = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"refresh_request", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_request
    {
      get { return _refresh_request; }
      set { _refresh_request = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo> _goods_list = new global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"goods_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo> goods_list
    {
      get { return _goods_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenStore")]
  public partial class OpenStore : global::ProtoBuf.IExtensible
  {
    public OpenStore() {}
    
    private fogs.proto.msg.StoreType _store_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.StoreType store_id
    {
      get { return _store_id; }
      set { _store_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenStoreResp")]
  public partial class OpenStoreResp : global::ProtoBuf.IExtensible
  {
    public OpenStoreResp() {}
    
    private fogs.proto.msg.StoreType _store_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.StoreType store_id
    {
      get { return _store_id; }
      set { _store_id = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo> _goods_list = new global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"goods_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo> goods_list
    {
      get { return _goods_list; }
    }
  
    private uint _next_refresh_time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"next_refresh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint next_refresh_time
    {
      get { return _next_refresh_time; }
      set { _next_refresh_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshStoreGoods")]
  public partial class RefreshStoreGoods : global::ProtoBuf.IExtensible
  {
    public RefreshStoreGoods() {}
    
    private fogs.proto.msg.StoreType _store_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.StoreType store_id
    {
      get { return _store_id; }
      set { _store_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshStoreGoodsResp")]
  public partial class RefreshStoreGoodsResp : global::ProtoBuf.IExtensible
  {
    public RefreshStoreGoodsResp() {}
    
    private fogs.proto.msg.StoreType _store_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.StoreType store_id
    {
      get { return _store_id; }
      set { _store_id = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.StoreRefreshType _oper_type = fogs.proto.msg.StoreRefreshType.SRT_OPEN;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"oper_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fogs.proto.msg.StoreRefreshType.SRT_OPEN)]
    public fogs.proto.msg.StoreRefreshType oper_type
    {
      get { return _oper_type; }
      set { _oper_type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo> _goods_list = new global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"goods_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.StoreGoodsInfo> goods_list
    {
      get { return _goods_list; }
    }
  
    private uint _next_refresh_time = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"next_refresh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint next_refresh_time
    {
      get { return _next_refresh_time; }
      set { _next_refresh_time = value; }
    }
    private uint _refresh_request = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"refresh_request", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_request
    {
      get { return _refresh_request; }
      set { _refresh_request = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyStoreGoodsInfo")]
  public partial class BuyStoreGoodsInfo : global::ProtoBuf.IExtensible
  {
    public BuyStoreGoodsInfo() {}
    
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyStoreGoods")]
  public partial class BuyStoreGoods : global::ProtoBuf.IExtensible
  {
    public BuyStoreGoods() {}
    
    private fogs.proto.msg.StoreType _store_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.StoreType store_id
    {
      get { return _store_id; }
      set { _store_id = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.BuyStoreGoodsInfo> _info = new global::System.Collections.Generic.List<fogs.proto.msg.BuyStoreGoodsInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.BuyStoreGoodsInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyStoreGoodsResp")]
  public partial class BuyStoreGoodsResp : global::ProtoBuf.IExtensible
  {
    public BuyStoreGoodsResp() {}
    
    private fogs.proto.msg.StoreType _store_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.StoreType store_id
    {
      get { return _store_id; }
      set { _store_id = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.BuyStoreGoodsInfo> _info = new global::System.Collections.Generic.List<fogs.proto.msg.BuyStoreGoodsInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.BuyStoreGoodsInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"StoreType")]
    public enum StoreType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_BLACK", Value=1)]
      ST_BLACK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_SKILL", Value=2)]
      ST_SKILL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_FASHION", Value=3)]
      ST_FASHION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_HONOR", Value=4)]
      ST_HONOR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_TOUR", Value=5)]
      ST_TOUR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_REPUTATION", Value=6)]
      ST_REPUTATION = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_EXP", Value=7)]
      ST_EXP = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_OTHER", Value=8)]
      ST_OTHER = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"StoreRefreshType")]
    public enum StoreRefreshType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRT_OPEN", Value=1)]
      SRT_OPEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRT_SELF_REFRESH", Value=2)]
      SRT_SELF_REFRESH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRT_SYSTEM_REFRESH", Value=3)]
      SRT_SYSTEM_REFRESH = 3
    }
  
}