//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cfg/RoleBase.proto
namespace Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleBase")]
  public partial class RoleBase : global::ProtoBuf.IExtensible
  {
    public RoleBase() {}
    
    private readonly global::System.Collections.Generic.List<Config.RoleBase.Item> _item = new global::System.Collections.Generic.List<Config.RoleBase.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Config.RoleBase.Item> item
    {
      get { return _item; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _cls;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cls", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cls
    {
      get { return _cls; }
      set { _cls = value; }
    }

    private int _brief = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"brief", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int brief
    {
      get { return _brief; }
      set { _brief = value; }
    }

    private int _act_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"act_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int act_id
    {
      get { return _act_id; }
      set { _act_id = value; }
    }

    private int _prop = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"prop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int prop
    {
      get { return _prop; }
      set { _prop = value; }
    }

    private int _equip_a = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"equip_a", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip_a
    {
      get { return _equip_a; }
      set { _equip_a = value; }
    }

    private int _equip_b = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"equip_b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip_b
    {
      get { return _equip_b; }
      set { _equip_b = value; }
    }

    private int _equip_c = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"equip_c", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip_c
    {
      get { return _equip_c; }
      set { _equip_c = value; }
    }

    private int _equip_d = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"equip_d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip_d
    {
      get { return _equip_d; }
      set { _equip_d = value; }
    }

    private int _equip_e = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"equip_e", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip_e
    {
      get { return _equip_e; }
      set { _equip_e = value; }
    }

    private int _equip_f = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"equip_f", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip_f
    {
      get { return _equip_f; }
      set { _equip_f = value; }
    }

    private int _equip_g = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"equip_g", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip_g
    {
      get { return _equip_g; }
      set { _equip_g = value; }
    }

    private int _equip_h = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"equip_h", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip_h
    {
      get { return _equip_h; }
      set { _equip_h = value; }
    }

    private int _ability_a = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"ability_a", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ability_a
    {
      get { return _ability_a; }
      set { _ability_a = value; }
    }

    private int _ability_b = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"ability_b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ability_b
    {
      get { return _ability_b; }
      set { _ability_b = value; }
    }

    private int _ability_c = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"ability_c", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ability_c
    {
      get { return _ability_c; }
      set { _ability_c = value; }
    }

    private int _ability_d = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"ability_d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ability_d
    {
      get { return _ability_d; }
      set { _ability_d = value; }
    }

    private int _ability_e = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"ability_e", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ability_e
    {
      get { return _ability_e; }
      set { _ability_e = value; }
    }

    private int _ability_f = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"ability_f", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ability_f
    {
      get { return _ability_f; }
      set { _ability_f = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}